 <div style=" text-align:right;"><em>"Hay hombres que luchan un d&iacute;a y son buenos. <br>
Hay otros que luchan un a&ntilde;o y son mejores. <br>
Hay quienes luchan muchos a&ntilde;os, y son muy buenos. <br>
Pero hay los que luchan toda la vida: <br>
esos son los imprescindibles". <br>
<br> 
Bertolt Brecht</em>
</div> 
  
  
  
 
 <p style="text-align:justify">Si hay que acu&ntilde;ar una imagen de Iv&aacute;n Nu&ntilde;ez Prieto, es la de un hombre que  ha sido generador de conocimiento en educaci&oacute;n, &nbsp;que ha contribuido al dise&ntilde;o de importantes  pol&iacute;ticas p&uacute;blicas y a la formaci&oacute;n de nuevos historiadores de la educaci&oacute;n en  Chile. </p>
 <p style="text-align:justify">Desde los a&ntilde;os 50', cuando reci&eacute;n egresaba del Instituto Pedag&oacute;gico como  Profesor de Historia y Geograf&iacute;a, su marcado rigor lo convirti&oacute; muy r&aacute;pidamente  en parte del equipo del primer centro de investigaci&oacute;n especializada en educaci&oacute;n,  que fuera creado por Juan Gomez Millas y que dirigiera Irma Salas en la  Universidad de Chile. Las pol&iacute;ticas educativas fueron su dedicaci&oacute;n, adem&aacute;s de  su ejercicio docente en liceos de la periferia de Santiago. En 1970 asumi&oacute; como  Superintendente de Educaci&oacute;n &nbsp;P&uacute;blica  durante el Gobierno del Presidente Allende, posibilitando la concreci&oacute;n de la  reforma curricular que se iniciara en el Gobierno de Frei Montalva y &nbsp;propiciando  una reforma curricular que integraba la educaci&oacute;n general y la educaci&oacute;n para  el trabajo. </p>
 <p style="text-align:justify">En los  dif&iacute;ciles a&ntilde;os que siguieron, trabaj&oacute; en los organismos no gubernamentales  dedicados a la investigaci&oacute;n en Educaci&oacute;n -el CIDE y posteriormente en el PIIE-  del que fuera su director entre 1981 y 1987. El conocimiento acad&eacute;mico y  aplicado que &eacute;l desarroll&oacute; y potenci&oacute;, permiti&oacute; sustentar la reflexi&oacute;n  educativa, ausente del quehacer universitario de aquel entonces. M&aacute;s de 50  publicaciones y art&iacute;culos permitieron dejar registro de ello. Su inquebrantable  empe&ntilde;o en favor de la educaci&oacute;n p&uacute;blica y el desarrollo docente, as&iacute; como la  rigurosidad y expansi&oacute;n de su pensamiento han aportado en forma&nbsp; relevante a la formaci&oacute;n inicial de  profesores y a su desarrollo profesional, como dan testimonio de ello docentes  a lo largo de Chile. &nbsp;Tambi&eacute;n le han  valido el reconocimiento de importantes historiadores del pa&iacute;s, siendo sus  textos, &ldquo;citas obligadas&rdquo; de la historia de la educaci&oacute;n chilena. En el a&ntilde;o que  se anuncia como el a&ntilde;o de la educaci&oacute;n p&uacute;blica y la nueva carrera docente, qu&eacute;  mejor que reconocer a quien ha aportado tanto a ambos empe&ntilde;os de la sociedad  chilena. &nbsp;</p>
 <p style="text-align:justify">Con el  regreso de la Democracia asumi&oacute; como representante del Presidente de la  Rep&uacute;blica en la Junta Directiva de la Universidad Metropolitana de Ciencias de  la Educaci&oacute;n, UMCE.&nbsp; Tambi&eacute;n asesor&oacute; al  Ministerio de Educaci&oacute;n desde el 90' hasta el 2008 en diversas tareas,  comisiones y programas, asumiendo un rol protag&oacute;nico en la elaboraci&oacute;n de  varios proyectos de ley. Destacan entre ellos, el Estatuto de la Profesi&oacute;n  Docente, la Reforma Constitucional que estableci&oacute; los 12 a&ntilde;os de educaci&oacute;n  obligatoria, las normas legales sobre Evaluaci&oacute;n del Desempe&ntilde;o Profesional de  los Docentes, la Asignaci&oacute;n de Excelencia Pedag&oacute;gica, la Red Maestros de  Maestros. &nbsp;Este &uacute;ltimo a&ntilde;o fue instituido  con la Orden al M&eacute;rito Docente y Cultural &ldquo;Gabriela Mistral&rdquo;. Durante este  per&iacute;odo Iv&aacute;n N&uacute;&ntilde;ez nunca abandon&oacute; su labor como productor de conocimiento sobre  la educaci&oacute;n y su historia. Ejemplo de ello es su trabajo, desde 2008, como  investigador asociado en el Proyecto &nbsp;Anillo de Investigaci&oacute;n Social de la  Pontificia Universidad Cat&oacute;lica de Chile sobre la historia de la educaci&oacute;n  escolar desde la Independencia hasta 2010. Actualmente, a sus 83 a&ntilde;os, sigue  trabajando en lo que ha sido la dedicaci&oacute;n de su vida, contribuyendo tambi&eacute;n a  la formaci&oacute;n de nuevas generaciones dedicadas a la historia de la educaci&oacute;n  chilena.</p>


