<div class="titulo_1_noticia_azul_oscuro"><a name="financiamiento"></a>Financiamiento compartido</div>
  <p>Datos: El financiamiento compartido se crea en 1988 y se reforma en 1993, permitiendo su expansi&oacute;n. Hoy el 70% de la matr&iacute;cula particular subvencionada est&aacute; bajo esta modalidad. El l&iacute;mite m&aacute;ximo de cobro a las familias es de $ 85 mil.</p>
  <p>Reforma: se propone eliminar el financiamiento compartido en un plazo de 10 a&ntilde;os, aumentando gradualmente la Subvenci&oacute;n Escolar Preferencial (SEP) hasta llegar al 80% de las familias del pa&iacute;s. Esto operar&iacute;a s&oacute;lo para los colegios subvencionados que firmen convenios con el Estado. Adem&aacute;s, se crear&aacute; una subvenci&oacute;n para la gratuidad.</p>
  
   <div class="titulo_2_noticia_azul_oscuro">La gratuidad como un derecho y condici&oacute;n para una educaci&oacute;n de calidad para todos</div>
   
   <p> <strong>Art&iacute;culo de Juan Pablo Valenzuela.</strong> </p>
   <p>El art&iacute;culo hace una revisi&oacute;n de la evidencia existente acerca de los efectos del financiamiento compartido y concluye que el t&eacute;rmino de este mecanismo –que nunca debi&oacute; haberse incluido en el sistema escolar chileno– ampliar&aacute; las oportunidades educativas de los ni&ntilde;os y j&oacute;venes, especialmente de los grupos medios y vulnerables, mejorar&aacute; las oportunidades para que el sistema escolar cumpla de mejor forma su objetivo de cohesi&oacute;n e integraci&oacute;n social, del ejercicio de la tolerancia, convivencia y respeto de la diversidad, como tambi&eacute;n pondr&aacute; nuevamente a la escuela como una instituci&oacute;n que permite fortalecer nuestra identidad y cultura nacional. Aunque no por ello, agrega el autor, resuelve los desaf&iacute;os de asegurar una educaci&oacute;n de calidad para todos los ni&ntilde;os y j&oacute;venes de nuestro pa&iacute;s.</p>
   <p> <strong> <a href="download.php?file=noticias/511/La_gratuidad_como_un_derechoJPV.pdf" target="_blank">Lea el art&iacute;culo completo.</a> </strong> </p>
  
  <div class="titulo_2_noticia_azul_oscuro">¿Cu&aacute;l es el efecto del financiamiento compartido sobre el rendimiento escolar, medido en pruebas Simce?</div>
  <p> <strong>Tesis de mag&iacute;ster</strong> </p>
  <p>¿Cu&aacute;l es el efecto del financiamiento compartido sobre el rendimiento escolar, medido en pruebas Simce? Es lo que determin&oacute; una tesis del Mag&iacute;ster de Econom&iacute;a Aplicada del Departamento de Ingenier&iacute;a Industrial de la Universidad de Chile, de Trinidad Saavedra, dirigida por la directora del departamento y directora acad&eacute;mica del CIAE, Alejandra Mizala.</p>
  <p>El estudio concluye que, tras corregir el sesgo de selecci&oacute;n, las diferencias de puntajes entre colegios subvencionados con financiamiento compartido y subvencionados gratuitos se reducen. Pasan de 19 puntos (sin corregir) a 6 puntos en matem&aacute;ticas, mientras que en lenguaje la brecha baja de 13 puntos (sin corregir) a pr&aacute;cticamente cero.</p>
  <p>En la tesis tambi&eacute;n se analiz&oacute; si hay efectos heterog&eacute;neos del financiamiento compartido sobre los resultados del SIMCE, asociados a los a&ntilde;os que los establecimientos llevan en el sistema y al monto cobrado a los padres. Para el caso de la prueba de lenguaje, no se aprecian diferencias entre los colegios que cobran y los gratuitos, independiente de los a&ntilde;os que el colegio lleve en el sistema. Seg&uacute;n el monto cobrado a los padres, no existen diferencias entre el puntaje SIMCE de matem&aacute;ticas de los alumnos que asisten a establecimientos que tienen 16 a&ntilde;os de financiamiento compartido y que cobran menos de $8.000 mensuales, y el puntaje de los alumnos que asisten a establecimientos gratuitos.</p>
  <p> <strong> <a href="download.php?file=noticias/511/Tesis_Trinidad_Saavedra.pdf" target="_blank">Lea la tesis completa. </a> </strong> </p>
  <div class="titulo_2_noticia_azul_oscuro">¿C&oacute;mo debe operar la eliminaci&oacute;n del financiamiento compartido?</div>
  <p> <strong>Exposici&oacute;n de Juan Pablo Valenzuela, ante el Colegio de Profesores el 7 de mayo de 2014</strong> </p>
  <p>Por eficiencia, efectividad y equidad el financiamiento debiese ser eliminado, plante&oacute; el acad&eacute;mico del CIAE, Juan Pablo Valenzuela. ¿C&oacute;mo debe operar dicha eliminaci&oacute;n? Debe ser gradual, con foco en promover la recomposici&oacute;n social de los colegios m&aacute;s que en compensar monetariamente hacia arriba y dise&ntilde;ar un mecanismo para que un alto porcentaje de colegios sea gratuito al inicio de la reforma.</p>
  <p>Presentaci&oacute;n incluye, adem&aacute;s, cu&aacute;les son los efectos del mecanismo sobre la equidad, efectividad y eficiencia en el sistema.</p>
  <p> <strong> <a href="download.php?file=noticias/511/Presentacion_Colegio_de_Profesores_mayo_2014.pdf" target="_blank">Mire la presentaci&oacute;n.</a> </strong> </p>
  <div class="titulo_2_noticia_azul_oscuro">¿Qu&eacute; efectos ha tenido la Subvenci&oacute;n Escolar Preferencial?</div>
  <p> <strong>Estudio de Alejandra Mizala y Florencia Torche</strong> </p>
  <p>Estudio analiza el efecto de la Subvenci&oacute;n Escolar Preferencial, instaurada desde 2008 y que da recursos adicionales por alumno vulnerable, sobre los establecimientos. Concluye que los colegios particular subvencionados, luego de ingresar a la SEP, aumentaron en promedio sus puntajes en la prueba Simce. Este efecto positivo aumenta con los a&ntilde;os de exposici&oacute;n a la SEP: entre las escuelas que ingresaron al sistema en 2008, el Simce aument&oacute; 2 puntos en 2009, 4,6 puntos para las que la implementaron desde 2010; y 6,8 puntos para las que lo aplicaron desde 2011. Para matem&aacute;ticas se observa el mismo patr&oacute;n, con una ganancia acumulada de 3 puntos en 2009, 5 puntos en 2010 y 10 puntos en 2011. Esto sugiere que los colegios requieren tiempo para hacer un uso &oacute;ptimo de los recursos que conlleva la SEP.</p>
  <p>Las escuelas del quintil m&aacute;s pobre fueron las que experimentaron mayores aumentos: 13 puntos para matem&aacute;ticas, 10 puntos para lenguaje. Adem&aacute;s, el efecto aumenta significativamente para estas escuelas con el tiempo. Las autoras concluyen que la SEP obtiene resultados alineados con sus objetivos, esto es, logra mejorar los resultados educativos, medidos por las pruebas estandarizadas, por lo que recomiendan que es importante seguir fortaleci&eacute;ndola.</p>
  <p> <strong> <a href="download.php?file=noticias/511/Mizala_and_Torche.pdf" target="_blank">Lea el estudio completo.</a> </strong> </p>
  <div class="titulo_1_noticia_azul_oscuro"><a name="lucro"></a>Lucro</div>
  <p>Datos: Hoy se permite el lucro en el sistema escolar con recursos p&uacute;blicos, mientras se proh&iacute;be a nivel de educaci&oacute;n superior. El 31% de la matr&iacute;cula escolar (m&aacute;s de un mill&oacute;n de alumnos) est&aacute; bajo esta modalidad.</p>
  <p>Reforma: se propone eliminar el lucro en todo el sistema escolar.</p>
  <div class="titulo_2_noticia_azul_oscuro">El &ldquo;fin de lucro&rdquo; como pol&iacute;tica educacional</div>
  <p> <strong>Art&iacute;culo de Cristi&aacute;n Bellei, publicado en &ldquo;Los fines de la educaci&oacute;n&rdquo;, CEPPE 2013.</strong> </p>
  <p>En el art&iacute;culo, el autor examina la evidencia en torno al lucro y concluye que existe suficiente evidencia sobre el tema que es neutra o negativa en t&eacute;rminos de calidad y eficiencia; existe evidencia consistentemente negativa en t&eacute;rminos de equidad y cohesi&oacute;n social; y existe algo de evidencia mixta en t&eacute;rminos de su aporte a la diversidad y la libertad de elecci&oacute;n. &ldquo;Si estuvi&eacute;ramos en un pa&iacute;s que est&aacute; discutiendo acerca de si introducir o no esta pol&iacute;tica a escala nacional, la recomendaci&oacute;n responsable &ndash;basada en la evidencia cient&iacute;fica- ser&iacute;a negativa&rdquo;, concluye Bellei.</p>
  <p> <strong> <a href="download.php?file=noticias/511/BELLEI_el_lucro_en_educacion.pdf" target="_blank">Lea el art&iacute;culo completo.</a> </strong> </p>
  <div class="titulo_1_noticia_azul_oscuro"><a name="seleccion"></a>Selecci&oacute;n y segregaci&oacute;n</div>
  <p>Datos: Pese a estar prohibida la selecci&oacute;n hasta sexto b&aacute;sico por la Ley General de Educaci&oacute;n, existe evidencia de que los colegios siguen estableciendo m&eacute;todos para seleccionar a sus alumnos. El sistema escolar chileno es uno de los m&aacute;s segregados del mundo.</p>
  <p>Reforma: se propone eliminar la selecci&oacute;n por parte de los colegios, estableciendo una plataforma coordinada por el Mineduc donde los padres puedan postular, despu&eacute;s de aceptar el proyecto educativo del colegio.</p>
  
  
  <div class="titulo_2_noticia_azul_oscuro">¿Qu&eacute; ha sucedido con los grupos medios?</div>
  <p> <strong>Art&iacute;culo de Juan Pablo Valenzuela, Crist&oacute;bal Villalobos, Gabriela G&oacute;mez</strong> </p>
  <p>El art&iacute;culo busca complementar y profundizar anteriores investigaciones sobre los procesos de segregaci&oacute;n y polarizaci&oacute;n del sistema escolar chileno -que presenta niveles extremos respecto al panorama internacional-.Con este fin, se analiza la distribuci&oacute;n de estudiantes pertenecientes a un grupo muy poco estudiado durante los &uacute;ltimos a&ntilde;os: los estudiantes de los grupos medios socioecon&oacute;micos. </p>
  <p>
Los resultados muestran que, tanto a nivel socioecon&oacute;mico como acad&eacute;mico, la distribuci&oacute;n de la segregaci&oacute;n educativa adquiere una forma de “U”, con niveles altos de segregaci&oacute;n en los extremos –especialmente en t&eacute;rminos socioecon&oacute;micos- pero con un comportamiento de meseta relativamente estable y elevado en el centro de la distribuci&oacute;n. Esto implica que son los estudiantes vulnerables y los de la &eacute;lite los que se encuentran m&aacute;s segregados del sistema escolar, y que los grupos medios presentan una situaci&oacute;n intermedia.
</p>
  
  <p> <strong> <a href="download.php?file=noticias/511/Que_ha_sucedido_con_los_grupos_medios_JPV.pdf" target="_blank">Lea el estudio completo.</a> </strong> </p>
  
  
  
  <div class="titulo_2_noticia_azul_oscuro">Segregaci&oacute;n socioecon&oacute;mica de las escuelas en un sistema educacional orientado por el mercado: el caso de Chile</div>
  <p> <strong>Estudio de Juan Pablo Valenzuela, Cristi&aacute;n Bellei y Danae de Los R&iacute;os publicado en </strong> <strong>Journal of Education Policy.</strong> </p>
  <p>La segregaci&oacute;n escolar es un 30% m&aacute;s alta que la residencial, mientras que algunas din&aacute;micas de mercado del sistema escolar, como privatizaci&oacute;n, capacidad de pago y elecci&oacute;n de escuelas, est&aacute;n vinculadas estrechamente con la segregaci&oacute;n escolar. El nivel de segregaci&oacute;n socioecon&oacute;mica de las escuelas chilenas ha tenido una tendencia al alza en la &uacute;ltima d&eacute;cada. Entre 1999 y 2008, el &iacute;ndice Duncan aument&oacute; de 0,51 a 0,54 para el 30% de estudiantes de cuarto b&aacute;sico de menores recursos y de 0,58 a 0,60 para los estudiantes del mismo grado, ubicados en el 30% de mayores recursos de la poblaci&oacute;n.</p>
  <p>&eacute;stas son algunas de las conclusiones del estudio &ldquo;Segregaci&oacute;n socioecon&oacute;mica de las escuelas en un sistema educacional orientado por el mercado: el caso de Chile&rdquo;, realizado por los investigadores Juan Pablo Valenzuela y Cristi&aacute;n Bellei, del Centro de Investigaci&oacute;n Avanzada en Educaci&oacute;n de la U. de Chile; y Danae de Los R&iacute;os, de la Universidad Diego Portales.</p>
  <p> <strong> <a href="download.php?file=noticias/511/JPV_BELLEI_DANAE_SES_Segregation_in_Chile.pdf" target="_blank">Lea el estudio completo.</a> </strong> </p>
  <div class="titulo_2_noticia_azul_oscuro">Estratificaci&oacute;n de la educaci&oacute;n en Chile</div>
  <p> <strong>Estudio de Alejandra Mizala y Florencia Torche, publicado en la revista <em>International Journal of Educational Development </em> </strong> </p>
  <p>Este estudio muestra que el sistema educacional en nuestro pa&iacute;s ha generado una forma particular de estratificaci&oacute;n.  Contrario a la visi&oacute;n simplificada, en la cual los colegios particulares subvencionados atraer&iacute;an a los &ldquo;mejores estudiantes&rdquo; de los colegios municipales (l&eacute;ase de un nivel socioecon&oacute;mico m&aacute;s alto) <br /> -para dejar a los m&aacute;s pobres en estos establecimientos-, los datos muestran que el sistema particular subvencionado atiende a familias de un amplio espectro socioecon&oacute;mico, si bien al interior de cada uno de los colegios el nivel socioecon&oacute;mico de los estudiantes es muy homog&eacute;neo.</p>
  <p>Esto implica que el sector particular subvencionado se ve inclusivo, porque hay todo tipo de colegios, es decir, desde colegios para la clase media acomodada hasta colegios para pobres. Sin embargo, la unidad de an&aacute;lisis relevante no es el sector a nivel agregado, sino el colegio. En particular, el estudio encontr&oacute; que los establecimientos particulares subvencionados estratifican por nivel socioecon&oacute;mico y consecuentemente por resultados acad&eacute;micos; as&iacute; hay colegios particulares subvencionados para ni&ntilde;os acomodados y con buenos resultados escolares, y colegios para ni&ntilde;os pobres con peores resultados acad&eacute;micos.</p>
  <p>La pronunciada estratificaci&oacute;n econ&oacute;mica del sector particular subvencionado tambi&eacute;n se manifiesta en la elevada asociaci&oacute;n que existe entre el nivel socioecon&oacute;mico del colegio (que es el promedio del nivel socioecon&oacute;mico de todos los alumnos) y los resultados en el SIMCE. Esta asociaci&oacute;n es m&aacute;s del doble en tama&ntilde;o en los colegios particulares subvencionados que en los colegios municipales, aun despu&eacute;s de aislar el impacto del nivel socioecon&oacute;mico individual. En otras palabras, el resultado educativo de un estudiante que asiste a un colegio particular subvencionado depende en gran medida de la composici&oacute;n socioecon&oacute;mica del alumnado del colegio al que va, lo que significa que nuestras aulas no tienen la capacidad de interrumpir la reproducci&oacute;n cultural de la pobreza.</p>
  <p> <strong> <a href="download.php?file=noticias/511/IJED_32_(2012).pdf" target="_blank">Lea el estudio completo.</a> </strong> </p>
  <p> </p>
  <div class="titulo_2_noticia_azul_oscuro">Selecci&oacute;n e integraci&oacute;n social, ¿asignatura pendiente?</div>
  <p> <strong>Art&iacute;culo de Cristi&aacute;n Bellei, Juan Pablo Valenzuela, Danae de Los R&iacute;os</strong> </p>
  <p>El art&iacute;culo demuestra que el sistema escolar tiene una responsabilidad espec&iacute;fica en la producci&oacute;n de la segregaci&oacute;n escolar: mientras en algunos contextos el sistema escolar puede mitigar en parte la segregaci&oacute;n residencial, en el caso chileno ocurre lo contrario. Ciertos dispositivos educacionales contribuyen a aumentarla, de forma que los ni&ntilde;os y j&oacute;venes chilenos se encuentran socioecon&oacute;micamente m&aacute;s segregados en sus escuelas y liceos que en sus barrios y ciudades.</p>
  <p>Es probable que un sistema escolar segregado beneficie (por ejemplo, en t&eacute;rminos de logros acad&eacute;micos) a quienes no son parte de los grupos vulnerables o, al menos, a quienes conforman los grupos privilegiados de la sociedad. Todo lo anterior sugiere que las pol&iacute;ticas de combate a la segregaci&oacute;n escolar enfrentar&aacute;n enormes dificultades para generar consensos amplios en torno suyo.</p>
  <p> <strong> <a href="download.php?file=noticias/511/BELLEI_JPV_segregacion_en_Elacqua_y_Martinic.pdf" target="_blank">Lea el art&iacute;culo completo.</a> </strong> </p>
  
    <div class="titulo_1_noticia_azul_oscuro"><a name="educacion_publica"></a>Educaci&oacute;n p&uacute;blica</div>
  <p>Datos: La educaci&oacute;n p&uacute;blica atiende hoy al 36% de la matr&iacute;cula escolar del pa&iacute;s. Hasta la reforma del 80, las escuelas p&uacute;blicas depend&iacute;an del Estado y sus profesores eran funcionarios p&uacute;blicos. La reforma traspas&oacute; la administraci&oacute;n de las escuelas a los municipios y los docentes pasaron a regirse por el C&oacute;digo Laboral, hasta 1991 cuando se crea el Estatuto Docente.</p>
  <p>Reforma: durante el segundo semestre se enviar&aacute; proyecto para desmunicipalizar la educaci&oacute;n p&uacute;blica.
</p>
  <div class="titulo_2_noticia_azul_oscuro">Fortalecer la educaci&oacute;n p&uacute;blica: un desaf&iacute;o de inter&eacute;s nacional</div>
  <p> <strong>Art&iacute;culo de Cristi&aacute;n Bellei, Pablo Gonz&aacute;lez y Juan Pablo Valenzuela</strong> </p>
  <p>El art&iacute;culo expone y fundamenta una propuesta de fortalecimiento de la educaci&oacute;n p&uacute;blica chilena. Para ello, se propone una nueva agencia administradora y un cambio de dependencia institucional de la educaci&oacute;n. Adem&aacute;s, sugiere una estrategia integral para revitalizar la educaci&oacute;n p&uacute;blica, resolviendo, por ejemplo, las asimetr&iacute;as que hoy operan sobre quienes reciben financiamiento del Estado.</p>
  <p> <strong> <a href="download.php?file=noticias/511/BELLEI_PG_JPV_Educacion_Publica.pdf" target="_blank">Lea el estudio ac&aacute;.</a> </strong> </p>
  <div class="titulo_2_noticia_azul_oscuro">C&oacute;mo debe ser la nueva institucionalidad de la educaci&oacute;n p&uacute;blica</div>
  <p> <strong>Presentaci&oacute;n de Cristi&aacute;n Bellei en seminario del CEP</strong> </p>
  <p>En esta presentaci&oacute;n en el CEP, el acad&eacute;mico Cristi&aacute;n Bellei plantea una nueva institucionalidad para la administraci&oacute;n de las escuelas p&uacute;blicas, que incluya la creaci&oacute;n de agencias locales especializadas con funci&oacute;n &uacute;nica y que sean descentralizadas administrativa y financieramente.</p>
   <p> <strong> <a href="download.php?file=noticias/511/BELLEI_Educacion_Publica_CEP.pdf" target="_blank">Vea la presentaci&oacute;n ac&aacute;.</a> </strong> </p>