<p><strong style="text-transform:uppercase">Resumenes de presentaciones </strong></p>
<ul>
  <li><strong>David Whitebread</strong></li>
 
<p><strong>School Readiness:  &iquest;Qui&eacute;n necesita estar listo, el ni&ntilde;o o la escuela?</strong><br>
  <em>David Whitebread, PEDAL  Center, Universidad de Cambridge.</em></p>
<p align="left">Este paper trata sobre  el actual debate relacionado al school readiness. Se realiza una revisi&oacute;n a las  posiciones actuales sobre la edad de ingreso a la educaci&oacute;n, pol&iacute;ticas de  admisi&oacute;n y el curr&iacute;culo educacional en los primeros a&ntilde;os del Reino Unido, compar&aacute;ndolas  con otros ejemplos internacionales. Esto es seguido de un an&aacute;lisis cr&iacute;tico de  la evidencia investigativa proveniente de comparaciones internacionales, y de  la psicolog&iacute;a del desarrollo, orientado a c&oacute;mo aprenden los ni&ntilde;os. Se indican  aspectos del desarrollo temprano que son cruciales para el desarrollo saludable  y se exploran las implicancias que estos tienen para la calidad en educaci&oacute;n  temprana. </p>
 
  <li><strong>Kristiina Kumpulainen</strong></li>
 
<p><strong>Juego  y Aprendizaje en la Pol&iacute;tica y Pr&aacute;ctica Educativa Finlandesa</strong><br>
<em>Kristiina  Kumpulainen, Acad&eacute;mico Titular en Educaci&oacute;n, Playful Learning Center,  Departamento de Educaci&oacute;n para Profesores, Universidad de Helsinki</em></p>
<p>El juego es un asunto serio para los  ni&ntilde;os peque&ntilde;os de casi todas las culturas. Esto es evidente en el compromiso  apasionado, intenso, y energ&eacute;tico que muchos ni&ntilde;os invierten en esta actividad.  Se ha reconocido ampliamente que las experiencias de juego constituyen los  fundamentos de un desarrollo hol&iacute;stico y saludable. En Finlandia, las  oportunidades dadas para el juego son valoradas altamente en la educaci&oacute;n de  los ni&ntilde;os meores de siete a&ntilde;os, y &uacute;ltimamente el inter&eacute;s hacia el juego y el  aprendizaje a trav&eacute;s del juego se ha visto extendido a la educaci&oacute;n de ni&ntilde;os  m&aacute;s grandes, e incluso de adultos. En mi charla, reflexionar&eacute; sobre la  investigaci&oacute;n internacional actual enfocada en el juego y desarrollo y c&oacute;mo  esta evidencia cient&iacute;fica se toma en cuenta en la educaci&oacute;n Finlandesa, tanto  en su pol&iacute;tica p&uacute;blica como en la pr&aacute;ctica. Llamar&eacute; la atenci&oacute;n sobre  posibilidades y gatilladores, y mostrar&eacute; c&oacute;mo el juego y aprendizaje tambi&eacute;n  tratan sobre jugar con aprendizaje. Cerrar&eacute; mi charla considerando las  cambiantes panor&aacute;micas de juego en la era digital y sus consecuencias para el  aprendizaje de los ni&ntilde;os, la pr&aacute;ctica educativa y las compentecias  profesionales de los profesores. </p>
 
  <li><strong>John Potter</strong></li>
 
<p><strong>Literacidades din&aacute;micas y aprendices  ag&eacute;nticos en sistemas est&aacute;ticos</strong><br>
<em>Dr John Potter</em><br>
  <em>Departmento de Cultura, Comunicaci&oacute;n and  Medios de Comunicaci&oacute;n&nbsp;</em><br>
  <em>University  College London Knowledge Lab </em><br>
  <em>UCL  Instituto de Educaci&oacute;n</em></p>
<p>La agencia  en contextos de aprendizaje es un asunto crucial para los sistemas educativos  alrededor del mundo, particularmente en aquellos lugares donde medidas  performativas amenazan con inhibir la habilidad de los ni&ntilde;os de aprender y la  habilidad de sus profesores de responder creativamente a sus necesidades. En el  contexto de un mayor uso de medios digitales y tecnolog&iacute;as este asunto ocupa un  disputado espacio entre el hogar y la escuela y trae consigo cuestionamientos  sobre tem&aacute;ticas m&aacute;s amplias de definiciones de "literacidad" y "agencia".&nbsp; &iquest;Qu&eacute; significa tener literacidad en el 2016?  &iquest;Qu&eacute; significa ser un aprendiz ag&eacute;ntico en el 2016? Bas&aacute;ndose en varios  proyectos investigativos recientes, mi charla explora la producci&oacute;n y curaci&oacute;n  medi&aacute;tica como un set de nuevas pr&aacute;cticas activas de literacidad en donde  ciertas disposiciones y habilidades estrat&eacute;gicas particulares son usadas por  ni&ntilde;os de primaria y secundaria baja (5 – 14 a&ntilde;os) para representar identidad,  afiliaci&oacute;n y capital cultural. Se considerar&aacute; la naturaleza de la respuesta  pedag&oacute;gica a estos cambios de paradigma en contextos educativos formales e  informales. Se introducir&aacute; el concepto de membrana semi-permeable entre el  hogar y la escuela como un tercer espacio y la ubicaci&oacute;n de un "poro experto"  que potencialmente promueve un compromiso m&aacute;s ag&eacute;ntico en el aprendizaje. Habr&aacute;  espacio para mostrar ejemplos de juego y discutirlos y debatirlos en el  contexto de las teor&iacute;as expuestas. </p>
 
  <li><strong>Cristina Schmitt</strong></li>
 
<p><strong>Agencia desde un punto de vista  ling&uuml;&iacute;stico: Por qu&eacute; existe una desconexi&oacute;n entre la competencia ling&uuml;&iacute;stica de  los ni&ntilde;os y su desempe&ntilde;o en la escuela</strong><br>
<em>Cristina Schmitt, MSU Language  Acquisition Lab, Michigan State University</em></p>
<p>La noci&oacute;n de agencia es una idea  nuclear en la Educaci&oacute;n desde el Renacimiento (Biesta &amp; Tedder, 2006;  Duranti, 2000; Lantolf and Thome 2006; y Wertsch et al 1993; entre otros).  Todos podemos ver el valor de aprendices con iniciativa y habilidad para auto-regularse  e interactuar de un modo creativo y responsable con el contexto sociocultural y  todos podr&iacute;amos estar de acuerdo en que las escuelas y los profesores deben  crear un ambiente en donde los aprendices puedan de hecho ser agentes que se  involucran en su propio aprendizaje y toman responsabilidad por sus acciones.  Aunque el lenguaje media toda actividad en una escuela, existe una desconexi&oacute;n  entre la capacidad ling&uuml;&iacute;stica demostrable de los ni&ntilde;os y su habilidad para  auto-regularse, adaptarse a su complejo contexto ling&uuml;&iacute;stico y monitorear el  discurso de otros y su propia competencia en lo que aqu&iacute; llamamos dialecto  escolar. <br>
  Este paper se divide en tres partes.  En la primera parte examinamos lo que los ni&ntilde;os traen a la escuela en t&eacute;rminos  ling&uuml;&iacute;sticos. Tambi&eacute;n presentamos tres ejemplos de dialectos en espa&ntilde;ol que  colisionan m&aacute;s o menos radicalmente con las expectativas de la escuela. En la  segunda parte investigamos la brecha entre lo que pueden aprender  potencialmente y lo que pueden aprender realistamente dado su contexto. En  otras palabras, nos preguntamos hasta qu&eacute; punto la escuela provee las  herramientas que el aprendiz necesita para desarrollar el "dialecto escolar".  En la tercera parte realizamos propuestas concretas en dos frentes: primero  sugerimos un modo para utilizar comportamientos ling&uuml;&iacute;sticos como una medida de  involucramiento escolar; luego proponemos un set de medidas que podr&iacute;an  utilizarse para reducir la brecha entre el dialecto del ni&ntilde;o y las expectativas  de la escuela. Solo entonces nos encontraremos ante un espacio que conduce  aprendices ag&eacute;nticos. </p>
 
 
  <li><strong>Rob Yates</strong></li>
 
<p><strong>Transitar a la educaci&oacute;n media:  conceptualizando la agencia de la producci&oacute;n escrita de adolescentes dentro y  fuera del sal&oacute;n de clases de arte ling&uuml;&iacute;stico.</strong><br>
  <em>Rob Yates, Center for New Designs in Learning  &amp; Scholarship, Universidad de Georgetown, Estados Unidos. </em></p>
<p>El objetivo  general del sal&oacute;n de clases de artes del lenguaje es socializar a los  estudiantes para que puedan convertirse en lectores y escritores con agencia,  pero desarrollar un m&eacute;todo pedag&oacute;gico efectivo presenta varios desaf&iacute;os. &iquest;C&oacute;mo  construye el profesor una pedagog&iacute;a que navegue los temas, la pol&iacute;tica  cultural, y las teor&iacute;as sobre la literatura, al mismo tiempo que fomente la  apreciaci&oacute;n de las cualidades literarias? &iquest;C&oacute;mo construye el profesor una <em>entrance</em> a las obras sin reducir o  descuidar elementos importantes del texto. Muchas veces en los Estados Unidos,  el profesor de literatura utiliza una pedagog&iacute;a basada en mini-lecciones y  discusiones, la que enfatiza el an&aacute;lisis y escrutinio del texto, como tambi&eacute;n  una que explora los contextos hist&oacute;ricos y culturales de la literatura. Muy  apropiadamente, muchos curr&iacute;culos de las artes del lenguaje enfatizan la  comunicaci&oacute;n de este an&aacute;lisis en la escritura. En esta presentaci&oacute;n, exploro el  renovado inter&eacute;s en el aprendizaje basado en proyectos y en el desempe&ntilde;o en  educaci&oacute;n escolar, considerando las oportunidades de agencia aumentada para los  alumnos en la forma de escritura en el sal&oacute;n de clases de artes del lenguaje. Espec&iacute;ficamente,  considero c&oacute;mo el reciente trabajo de Nell Duke (2014) avanza la teor&iacute;a de John  Dewey de la educaci&oacute;n como experiencia, a medida que se relaciona con el  desarrollo del estudiante como escritor en educaci&oacute;n b&aacute;sica y media. Aunque no  sugiero que el aprendizaje basado en proyectos debiera ser el &uacute;nico enfoque  pedag&oacute;gico en el sal&oacute;n de artes del lenguaje, argumento en favor de su  legitimidad como m&eacute;todo para demostrar c&oacute;mo puede incluir elementos de la  pedagog&iacute;a basada en mini-lecciones y discusiones y al mismo tiempo incrementar  la agencia de los estudiantes como escritores. </p>
    <li><strong>Equipo Fonide</strong></li>
 
<p><strong>Transici&oacute;n  y Articulaci&oacute;n entre la Educaci&oacute;n Parvularia y el Primero B&aacute;sico </strong><br>
  Daniela S. Jadue Roa, Centro de Investigaci&oacute;n  Avanzada de Educaci&oacute;n, Universidad de Chile<br>
  Elisabet D&iacute;az Costa, Universidad Cat&oacute;lica de la  Sant&iacute;sima Concepci&oacute;n <br>
  Gabriela Baez Bargellini, Centro de Investigaci&oacute;n  Avanzada de Educaci&oacute;n, Universidad de Chile </p>
<p><strong>Resumen: </strong>En esta presentaci&oacute;n se introducir&aacute;n los resultados preliminares del  Proyecto FONIDE N&deg;911436 denominado <em>"Transici&oacute;n  y Articulaci&oacute;n entre la Educaci&oacute;n Parvularia y la Pedagog&iacute;a General B&aacute;sica:  Caracter&iacute;sticas y evaluaci&oacute;n". </em>Esta investigaci&oacute;n se llev&oacute; a cabo en 12  colegios de diferentes dependencias de la Regi&oacute;n Metropolitana y la Regi&oacute;n del  Biob&iacute;o. Es un estudio de car&aacute;cter cualitativo y metodolog&iacute;as m&uacute;ltiples (visuales  y participativas), priorizando los enfoques de derechos y de escucha para la  recolecci&oacute;n de datos. Teniendo en consideraci&oacute;n estudios internacionales en  esta l&iacute;nea, esta presentaci&oacute;n busca dialogar los resultados preliminares  obtenidos en seis casos de estudio, analizando las perspectivas de ni&ntilde;as y  ni&ntilde;os, equipos pedag&oacute;gicos y las pr&aacute;cticas de aula. Estos resultados muestran  elementos de continuidad, progresi&oacute;n y discontinuidad entre NT2 y NB1, desde  las perspectivas de los diferentes agentes educativos y en relaci&oacute;n al an&aacute;lisis  de las pr&aacute;cticas pedag&oacute;gicas observadas. Estos hallazgos permiten ahondar y  comprender los procesos de construcci&oacute;n de conocimiento que actualmente tienen  espacio en las pr&aacute;cticas pedag&oacute;gicas de aula y sugieren revisar las condiciones  en las que se est&aacute; llevando a cabo la promoci&oacute;n de agencia y autorregulaci&oacute;n  tanto para los ni&ntilde;os como para los equipos docentes en miras a mejorar los  aprendizajes en esta importante etapa de la vida infantil.</p>
<p>Daniela S. Jadue Roa es Doctora en  Educaci&oacute;n y Mag&iacute;ster en Psicolog&iacute;a y Educaci&oacute;n de la Universidad de Cambridge  en el Reino Unido. Adem&aacute;s es Educadora de P&aacute;rvulos y Profesora General B&aacute;sica  de la Pontificia Universidad Cat&oacute;lica de Chile. Actualmente se desempe&ntilde;a como  investigadora del &aacute;rea de Educaci&oacute;n Inicial del Centro de Investigaci&oacute;n  Avanzada en Educaci&oacute;n (CIAE) de la Universidad de Chile y es representante  regional para la Organizaci&oacute;n Europea de Investigaci&oacute;n en Educaci&oacute;n Inicial  (EECERA) en Chile. </p>
<p>Elisabet D&iacute;az Costa es Doctora en  Intervenci&oacute;n Pedag&oacute;gica y Psicopedag&oacute;gica de la Universidad de Granada en  Espa&ntilde;a. Es Educador de P&aacute;rvulos y Licenciado en Educaci&oacute;n&nbsp; de la Pontificia Universidad Cat&oacute;lica de  Chile y actualmente se desempe&ntilde;a como acad&eacute;mico de la Universidad Cat&oacute;lica de  la Sant&iacute;sima Concepci&oacute;n.<br>
  Gabriela B&aacute;ez  Bargellini es Master en Curriculum, Pedagog&iacute;a y Evaluaci&oacute;n del Instituto de  Educaci&oacute;n del University College en Londres en el Reino Unido. Tambi&eacute;n es  Educadora de P&aacute;rvulos y Profesora General B&aacute;sica de la Pontificia Universidad  Cat&oacute;lica de Chile. Actualmente se desempe&ntilde;a como investigadora en diferentes  proyectos de investigaci&oacute;n con tem&aacute;ticas relativas a la educaci&oacute;n inicial como  tambi&eacute;n en la ense&ntilde;anza estrat&eacute;gica de las ciencias b&aacute;sicas en educaci&oacute;n  superior.</p>
 </ul>