var contexto = ['Un personaje está constituido por un conjunto de elementos que el narrador toma de la realidad. Es un ser ficticio que el lector va conociendo a través de una serie de informaciones que, en un principio, proporciona el narrador. Cuando hay diálogos o monólogos, dicha información provendrá del mismo personaje o de otros, según los datos aportados en las conversaciones.</p>', 
'Los trabajos de los sociólogos han puesto de relieve un hecho capital: los parámetros del pensamiento no son universales y el útil mental de cada civilización, o desde un punto de vista más limitado, de cada sociedad, depende en gran medida de su constitución social…</p>',
'Única entre las grandes civilizaciones autóctonas que ha durado hasta nuestros días, la civilización china empezó, sin embargo, bastante tarde: la primera dinastía histórica, la de los Chang, se inicia hacia el año 1500 antes de nuestra era. Bajo esta dinastía se practicaba la fundición del cobre, la urbanización, se conocía la organización social en clases y por supuesto la escritura.</p>',
'En la literatura todo es metáfora, algo que dice algo distinto; un "no" puede ser un "sí" y esa es su libertad, su ángulo de trescientos sesenta grados abierto al mundo. En la literatura no cuentan las respuestas dadas por un escritor, sino las preguntas que éste plantea y que son siempre más amplias que toda respuesta, por exhaustiva que esta pueda ser. También en la vida, por lo demás, las personas que  cuentan no son tanto las que comparten nuestras respuestas sobre las cosas últimas, sino las que se plantean nuestras mismas preguntas en torno a esas cosas.</p>',
'Hay algo curioso en la relación entre viaje y escritura, que es parecida a la relación entre escritura y vida. Uno viaja o vive y luego intenta rescatar en la escritura eso que ha visto y ha vivido. Pero cuando pasa el tiempo, lo que en el momento de la experiencia parecía central, desaparece en el recuerdo. Y otro momento que parecía indiferente o insignificante, en el momento de la escritura se convierte en central.</p>' ,
'La aparición de unos cuantos cientos de voces extranjeras en la vigésima segunda edición del Diccionario académico ha producido algunas reacciones poco complacidas, incluso entre quienes cada día se ponen un slip, y no unos calzoncillos, o se introducen en unas pantys y no en unas medias. Y lo hacen, a veces, haciendo gestos de escándalo porque la Academia ha incrustado en las columnas de su diccionario esos huéspedes inhóspitos, aunque los resalte con la señal de alarma que son los caracteres itálicos. El idioma vive en la cabeza de los hablantes, en nuestra alma, dramáticamente, entre el rechazo de lo alienígena, porque nos desvirtúa, y la aceptación resignada o entusiasta de cuanto lo renueva y lo hace más útil para vivir con los tiempos.</p>',
'Se ha dicho que la imprenta es la madre de la civilización, y el papel, el medio que perpetúa las ideas y aspiraciones de los hombres, y ensancha su capacidad de comunicación y de diálogo. Pues bien, el papel y la imprenta son dos de los cuatro grandes inventos chinos, junto con la brújula y la pólvora, que contribuyeron a la modernización de Occidente. Uno y otra han tenido enormes repercusiones en la vida intelectual del hombre moderno. Piénsese en lo que ocurriría en la vida cotidiana de nuestra sociedad si se dejara de producir papel o no se conocieran las técnicas de impresión. Si bien es cierto que existen otros medios de información y comunicación, no pueden suplir la función del papel y de la imprenta, que es básica y permanente.</p>' ,
'El escritor Francisco Umbral ganó el premio más prestigioso de lengua castellana, el Cervantes. "Yo represento la posmodernidad y la ironía", dijo, luego de afirmar que el Quijote era un "pelmazo insoportable", que el gran escritor español era Quevedo y no Cervantes, y que ese premio (el Cervantes, precisamente) le había sido negado antes "por un voto".</p>' ,
'Considerando, primero que conviene estimular a las mujeres a que hagan estudios serios, sólidos, segundo que ellas pueden ejercer con ventajas algunas de las profesiones denominadas científicas, y tercero que importa facilitarles los medios de que puedan ganar la subsistencia por sí mismas, decreto: se declara que las mujeres deben ser admitidas a rendir exámenes para optar y obtener títulos profesionales, con tal de que ellas se sometan a las mismas disposiciones a que están sujetos los hombres.</p>',
'Biónica -biología más técnica- es el nombre de la revolucionaria disciplina que puede asegurar nuestra supervivencia. En la investigación se vale de los principios elaborados por la propia naturaleza a través de millones de años. En este banco de datos de la creación está almacenado todo lo que condujo a la selección de nuestra fauna y flora, aprovechando óptimamente las condiciones del entorno. Apenas existe un problema científico o tecnológico del que no se encuentre la salida a través de la biónica.</p>' ,
'Espacios modernos, donde los objetos de metal y vidrio son los protagonistas; ambientes cálidos, vivos, llenos de color; otros, poéticos, conceptuales, en los que lo importante es la atmósfera que se forma, que no responden a ninguna norma de decoración; además, los tradicionales, aquellos que siempre son acogedores y un tanto nostálgicos. De todo hay en Casa Mater: la muestra de decoración más importante de los últimos años en nuestro país.</p>' ,
'Hay cuatro metáforas que describen la relación entre el alma y el cuerpo: el alma es prisionera de la cárcel del cuerpo; el alma está confinada en una tumba: su cuerpo; el alma es una artesana cuyo instrumento es el cuerpo; el alma es el piloto y el cuerpo, su barco. Las cuatro comparaciones son usadas por Platón y revelan la tensión que aún hoy persiste en el asunto. Las dos primeras destacan la condición de víctima del alma en el cuerpo: debe sufrir las imposiciones perentorias de la vida orgánica. Las dos últimas metáforas señalan un movimiento inverso: es el alma quien domina su cuerpo, lo maneja como un instrumento, lo conduce en la dirección deseada, como el navegante a su barca.</p>',
'Ante una situación anormal, la reacción anormal constituye una conducta normal. Aun nosotros, los psiquiatras, esperamos que los recursos de un hombre ante una situación anormal, como la de estar internado en un asilo, sean anormales en proporción a su grado de normalidad. La reacción de un hombre tras su internamiento en un campo de concentración representa igualmente un estado de ánimo anormal, pero juzgada objetivamente es normal y, como más tarde demostraré, una reacción típica dadas las circunstancias.</p>',
'He pasado tres días extraños: el mar, la playa, los caminos me fueron trayendo recuerdos de otros tiempos. No sólo imágenes: también voces, gritos y largos silencios de otros días. Es curioso, pero vivir consiste en construir futuros recuerdos; ahora mismo, aquí frente al mar, sé que estoy preparando recuerdos minuciosos, que alguna vez me traerán la melancolía y la desesperanza. El mar está ahí, permanente y rabioso. Mi llanto de entonces, inútil; también inútiles mis esperas en la playa solitaria, mirando tenazmente al mar.</p>' ,
'Si a los Etruscos les preocupaba el futuro inmediato, el más lejano e inevitable, la muerte, los obsesionaba. Construían tumbas suntuosas, casi podríamos decir habitables, donde sus descendientes celebraban fiestas ceremoniales en su memoria. Estos ritos necrolátricos basados en la idea de la supervivencia del difunto en su sepultura, probablemente evolucionaron más tarde hacia una noción del paso a un más allá, pero existen muchas dudas acerca de cómo llegó a concebirse ese mundo ulterior.</p>' ,
'La propaganda crea y reproduce en escala ampliada el deseo de la adquisición vertiginosa. Esparce ante nuestros ojos el deleite de los objetos o de los servicios, todo lo escenifica en medio de la belleza y el confort. Los bebedores de cerveza son rubios y hermosos, los portadores de blue-jeans son seductores, apuestos. Pero los compradores de automóviles los superan a todos, reúnen las máximas cualidades. En sus cuerpos se refleja la máxima potencia. No solo están bien vestidos sino que también son elegantes, más hermosos aun que los otros. Se advierte que tienen la capacidad de adquirir todo lo que desean.</p>',
'El Muro de Berlín marcó parte de la historia del siglo veinte. Construido en 1961 por la antigua República Democrática Alemana para impedir el éxodo de sus habitantes a la Alemania Occidental, fue el máximo símbolo de la Guerra fría. Miles de personas intentaron atravesar esta barrera de cemento y de alambres de púa. Muchos lo consiguieron, pero 1065 murieron en el intento. Quince años después de la caída el 9 de noviembre de 1989, un museo privado quiso homenajear a esas víctimas con un memorial en el mítico Checkpoint Charlie. El memorial incluye la reconstrucción de doscientos metros de muro hechos con losas de hormigón salvada de la pared real, y pretende atraer grandes cantidades de turistas. Eso sí, la reconstrucción de este monumento ha sido marcada por la polémica. Los críticos sostienen que una réplica de tan fácil acceso es una distorsión de la realidad y no representa el muro que retuvo a tantas personas.</p>',
'Según una narración antigua, recogida por Simone de Beauvoir, el filósofo Cineas le preguntó a Pirro:<br>-Cuando hayas conquistado Grecia, ¿qué harás?<br>-¡Conquistaré África!<br>-¿Y luego?<br>-¡Conquistaré la India!<br>-¿Y luego?, siguió preguntando Cineas.<br>-Luego descansaré de mis esfuerzos...<br>-¿Y por qué, repuso Cineas, no empiezas a descansar ahora?</p>',
'A la lectura se le suelen asignar funciones relacionadas con lo cognoscitivo, lo afectivo y lo activo, es decir, con los tres ámbitos de la realización personal. Hay, sin embargo, otra función de la lectura no menos importante que las anteriores: su función social. Es un hecho que hay una fuerte correlación entre los hábitos de lectura de un pueblo y su desarrollo material y social. Las personas que no leen tienden a ser rígidas en sus ideas y acciones, y a guiar sus vidas y su trabajo por lo que se les trasmite directamente. La persona que lee abre su mundo. El hábito de la lectura tiende a formar personas abiertas al cambio, orientadas hacia el futuro, capaces de valorar la planificación y aceptar principios científicos y técnicos.</p>' ,
'Cuando el emperador Wu Ti murió en su vasto lecho, en lo más profundo del palacio imperial, nadie se dio cuenta. Todos estaban demasiado ocupados en obedecer sus órdenes. El único que lo supo fue Wong Mong, el Primer Ministro, hombre ambicioso que aspiraba al trono. No dijo nada y ocultó el cadáver. Transcurrió un año de increíble prosperidad para el imperio: Hasta que, por fin, Wong Mong mostró al pueblo el esqueleto pelado del difunto emperador. "¿Ven?" dijo. "Durante un año un muerto se sentó en el trono. Y quien realmente gobernó fui yo. Merezco ser emperador". El pueblo, complacido, lo sentó en el trono y luego lo mató, para que fuese tan perfecto como su predecesor y la prosperidad del imperio continuase.</p>' ,
'La manipulación del núcleo atómico y sus partículas ha dado lugar también a otro hecho sorprendente: la creación de elementos químicos artificiales que tienen más de noventa y dos protones en su núcleo, es decir, elementos que van más allá del uranio natural.</p>' ,
'Me parece injusto que exista la posibilidad de que Bomberos no pueda acceder a un seguro médico en caso de accidentes cuando se entregan diariamente, por la seguridad de los demás.</p>',
'En 1992, el grupo británico Iron Maiden debió suspender su visita a Chile luego de que diversos sectores, sobre todo religiosos, rechazaran su música por considerarla satánica. Sin embargo, Providencia Televisión, la empresa que había contratado al conjunto, descartó haber recibido presiones y afirmó que la presentación no se realizaría, debido a que el lugar previsto para el show, la Estación Mapocho, estaba ocupado ese día. No obstante, la productora recomendó a los integrantes del grupo que no vinieran a Chile ni siquiera como turistas. Cuatro años después, la banda pudo presentarse en Chile en el Teatro Monumental.</p>' ,
'Si miras a tu alrededor verás que está a todas horas junto a ti: en la ventana electrónica del televisor y en los muros de las calles, en las páginas de los periódicos y en las portadas de las revistas, en los programas de la radio y en los buzones de las casas, en los espectáculos deportivos y en los conciertos musicales. Es la publicidad. No eres tú quien la elige sino que es ella quien te elige a ti. Está allí donde tú estés y con sus formas atrevidas y sus mensajes insinuantes te observa, te habla e intenta seducirte. No sólo alude a los objetos sino que atrapa tu mirada, conversa contigo y te invita a vivir de una determinada manera. Lo de menos son las cualidades del producto: lo que de veras importa es seducirte con ingeniosos eslóganes y con imágenes deslumbrantes con el fin de hacerte creer algo y de convencerte de que hagas alguna cosa.</p>' ,
'Investigadores suecos afirman que las mujeres que se embarazan mediante una fertilización in vitro, presentan dos veces más dolor de espalda que aquellas que se embarazan por vía normal. Kristiansson y sus colaboradores de la Universidad de Uppsala estudiaron dos grupos, uno constituido por mujeres que lograron embarazo por fertilización in vitro y otro por vías normales. A todas les solicitaron que llevarán un recuento de los dolores de espalda que podrían presentarse durante la gestación. Los resultados mostraron que el primer grupo registró el doble de dolores de espalda que el grupo control. Al mismo tiempo observaron que las que presentaban mayor dolor también tenían valores sanguíneos más elevados de la hormona relaxín.</p>' ,
'Suelo ser excesivo. Confieso que he nacido para lo demasiado. No en todo, claro está, sólo en ciertos vicios y para ciertas aficiones. De las virtudes no hablaré, pero en alguna también me paso un poco, aunque Aristóteles me regañaría por creer que, si me paso, puedo seguir llamándola virtud. Leo demasiado, escribo demasiado, viajo demasiado, me encolerizo demasiado, quiero hacer el amor con demasiadas personas y cosas, me enamoro demasiado de quien no me quiere, hablo demasiado, tengo demasiadas opiniones y no me las callo, gesticulo demasiado, grito demasiado, pretendo saber de demasiadas cosas, me río demasiado, lloro demasiado, cultivo y provoco demasiadas animadversiones. Me deprimo más de lo debido y me divierto como un niño bobo, sin medida. Soy un pasota, pero no porque pase de todo, como se dice en España para indicar indiferencia, sino porque me paso en todo.</p>' ,
'El Tratado de Libre Comercio de Chile con EE. UU. implicará necesariamente que algunos sectores de nuestra economía se potencien y que otros se depriman. Las empresas nacionales deberán adaptarse a las nuevas condiciones y no hay que descartar que desaparezcan algunas y que surjan otras.</p>' ,
'La prensa tiene derecho a informar sobre la vida privada de las figuras públicas siempre que eso se justifique por motivos de interés público. Pero todos los ciudadanos tienen también derecho a la privacidad. De este modo, no es fácil definir los límites de la acción periodística y, si no hay un marco legal nítido, pueden producirse no pocos conflictos.</p>',
'Un joven jardinero persa dice a su príncipe:<br>-¡Sálvame! Encontré a la Muerte esta mañana. Me hizo un gesto de amenaza. Esta noche, por milagro, quisiera estar en Ispahán.<br>El bondadoso príncipe le presta sus caballos. Por la tarde, el príncipe encuentra a la Muerte y le pregunta:<br>-Esta mañana, ¿por qué hiciste un gesto de amenaza a nuestro jardinero?<br>-No fue un gesto de amenaza, le responde, sino un gesto de sorpresa. Pues lo veía lejos de Ispahán esta mañana y debo tomarlo esta noche en Ispahán.</p>',
'Para el habitante de Nueva York, París o Londres, la muerte es la palabra que jamás se pronuncia porque quema los labios. El mexicano, en cambio, la frecuenta, la burla, la acaricia, duerme con ella, la festeja, es uno de sus juguetes favoritos y su amor más permanente.</p>'];


var preguntas = ['¿Qué función cumplen, según lo leído, el diálogo y el monólogo en un relato? </p>',
'En lo fundamental, ¿a qué relación se refiere el texto? </p>',
'En síntesis, ¿cuál es el tema del fragmento anterior? </p>',
'¿Cuál es la idea central planteada en el fragmento? </p>',
'¿Cuál es la idea central planteada en el fragmento? </p>',
'¿Cuál es la idea central planteada en el fragmento? </p>',
'¿Cuál de las siguientes opciones sintetiza mejor el contenido fundamental del fragmento? </p>',
'¿Cuál es la finalidad comunicativa del texto anterior? </p>',
'De la lectura del fragmento anterior se puede concluir que las mujeres: </p>',
'Según el párrafo, ¿qué opción precisa mejor la importancia de la biónica? </p>',
'¿Cuál es la finalidad comunicativa central del fragmento anterior? </p>',
'A partir de lo expresado en el fragmento anterior, se puede inferir que el alma: </p>',
'¿Cuál de las siguientes opciones sintetiza mejor el contenido del párrafo anterior? </p>',
'Para el narrador del fragmento leído, la vida es: </p>',
'Se desprende del fragmento que los Etruscos eran principalmente: </p>',
'Según el autor, ¿Cuál es la finalidad de la propaganda? </p>',
'¿Cuál es el objetivo de la construcción del memorial? </p>',
'De acuerdo con el texto, ¿A qué se refiere esencialmente el último parlamento expresado por Pirro? </p>',
'¿En que se fundamenta la afirmación realizada en el texto anterior? </p>',
'De acuerdo con el pensamiento del pueblo: </p>',
'De lo afirmado en el párrafo anterior se puede inferir que: </p>',
'¿Cuál es la idea defendida por la emisora del texto anterior? </p>',
'Según el texto, ¿A qué se debió la suspensión de la visita del grupo Iron Maiden? </p>',
'¿Qué idea sobre la publicidad se deduce del fragmento? </p>',
'Según el texto, las mujeres que se embarazan por vía normal: </p>',
'Del fragmento se infiere que: </p>',
'¿Cuál es la tesis que subyace en el siguiente texto? </p>',
'¿Cuál es la tesis que subyace en el siguiente texto? </p>',
'Del texto se puede concluir que: </p>',
'En el párrafo leído, el autor pretende explicar que: </p>']

var alta = [' Entregan una característica detallada del personaje, a través de la voz narrativa. ',
'A la relación entre pensamiento y estructura social.',
'El origen de las grandes civilizaciones.',
'En la literatura como en la vida, todo es metáfora.',
'La escritura plasma los mejores momentos de los viajes.',
'La aparición del Diccionario Académico ha sido polémica.',
'La impresión de libros es más importante que otros medios de información y comunicación.',
'Caracterizar al Quijote como un pelmazo.',
'pueden rendir exámenes para optar y obtener títulos profesionales igual que los hombres.',
'La biónica es una disciplina que aprovecha las condiciones del entorno.',
'Promover la asistencia a un evento específico de decoración a través de una atractiva descripción.',
'es una realidad discutida por algunos.',
'Lo que es normal en un asilo es anormal en un campo de concentración.',
'preparar los recuerdos del mañana.',
'ritualistas y obsesivos.',
'Mostrar cuerpos que reflejan la máxima potencia.',
'Atraer a los turistas.',
'Al premio merecido después de tantos esfuerzos.',
'El hábito de la lectura y el progreso mantienen una relación inversamente proporcional.',
'sólo las leyes bastan para gobernarse.',
'el uranio es el elemento natural con el mayor número de protones en el núcleo.',
'Se debe crear un seguro médico especial para esta institución, pues es de alto riesgo.',
'A la temática satánica de las canciones del grupo.',
'La publicidad es dañina para sus receptores.',
'tienen dificultades durante el parto.',
'para Aristóteles la virtud estaba en el justo equilibrio.',
'Nuestra economía vivirá un proceso de ajuste a la nueva realidad.',
'El derecho a informar y el derecho a la privacidad son inconciliables.',
'la Muerte vaticina el futuro mediante gestos.',
'para el mexicano, la muerte es cotidiana.'];

var altb = ["Aportan informaciones con las que se reconstruye el personaje dentro de un relato. ",
"A la relación entre civilización y sociedad. ",
"El inicio de la civilización china. ",
"Las personas importantes comparten el gusto por la literatura. ",
"En los viajes es esencial el momento mismo de la escritura. ",
"Las personas escandalosas constantemente critican a la Academia. ",
"La imprenta y el papel han permitido el desarrollo de la civilización y la conservación de su cultura, y ambos son inventos chinos. ",
"Comparar a Cervantes con Quevedo. ",
"deben ser capaces de mantenerse económicamente de la misma forma que los hombres. ",
"La biónica puede asegurar nuestra existencia mediante la aplicación de técnicas copiadas de la naturaleza. ",
"Orientar la opción estética de un grupo de personas en lo que se refiere a la decoración de interiores. ",
"se da como existente, y sólo se discute su relación con el cuerpo. ",
"El concepto de normalidad es diferente para un psiquiatra que para nosotros. ",
"un recuerdo nostálgico. ",
"hedonistas y soñadores. ",
"Deleitar a sus receptores por medio de la belleza y el confort. ",
"Homenajear a quienes murieron. ",
"Al deseo de privilegiar el ocio por sobre el trabajo. ",
"Si no se lee, es imposible valorar la planificación y aceptar principios científicos. ",
"la muerte de Wu Ti fue una bendición. ",
"la creación de elementos químicos artificiales ha resultado de la manipulación del uranio. ",
"Bomberos debería tener acceso a un seguro médico, al que pueda recurrir en caso de accidente. ",
"A la inexistencia de un recinto adecuado para el recital. ",
"El receptor es habitualmente pasivo frente a la publicidad. ",
"sufren dolores de espalda. ",
"el sujeto sufre con su modo de vida. ",
"El TLC causará una completa transformación de la economía chilena. ",
"Se necesita un marco legal para delimitar lo público y lo privado en materia informativa. ",
"el jardinero era un hombre viejo. ",
"la muerte es distinta en las grandes ciudades."];

var altc = [ "Muestran las opiniones expuestas por los personajes en un relato. ",
"A la relación entre sociedad y constitución social. ",
"El inicio de la dinastía Chang. ",
"En la literatura como en la vida, lo importante son las preguntas. ",
"Los momentos triviales de los viajes, en la escritura se vuelven significativos. ",
"Las voces extranjeras viven una tensión entre la aceptación y el rechazo. ",
"Si desaparecieran el papel y la imprenta, se produciría un gran retraso en nuestra civilización. ",
"Dar a conocer al ganador del premio Cervantes. ",
"pueden ejercer profesiones científicas de la misma forma en que lo hacen los hombres. ",
"La biónica es una disciplina que tiene su origen en la ecología. ",
"Presentar positivamente las diversas tendencias del diseño de interiores a través de un comentario. ",
"es una noción que obedece a una visión pesimista de la vida. ",
"El ser humano se comporta de acuerdo con las circunstancias. ",
"la persistencia de la melancolía y la desesperanza. ",
"religiosos y precavidos. ",
"Provocar el deseo de la adquisición vertiginosa. ",
"Revivir un periodo histórico. ",
"A la inutilidad de tanto esfuerzo si el objetivo es el reposo. ",
"Las personas que leen son más flexibles en sus ideas y autónomas en su accionar. ",
"el mejor emperador es el que está muerto. ",
"a partir de la manipulación del núcleo se han creado elementos químicos naturales. ",
"Por el riesgo que corren diariamente, los bomberos deberían tener mejores condiciones de seguridad. ",
"A la influencia de grupos que rechazaban su música. ",
"La publicidad ejerce una influencia positiva sobre la sociedad. ",
"llevan un control grupal de su embarazo. ",
"el hombre excesivo es inmoral. ",
"Será difícil que las empresas nacionales compitan con las estadounidenses. ",
"La prensa tiene derecho a meter sus narices en todos lados. ",
"el jardinero estará muerto al día siguiente. ",
"para el mexicano, la muerte es como una mujer."];


var condicion1_a = 
["Entregan una característica detallada del personaje, a través de la voz narrativa. ",
"A la relación entre pensamiento y estructura social. ",
"El origen de las grandes civilizaciones. ",
"En la literatura como en la vida, todo es metáfora. ",
"La escritura plasma los mejores momentos de los viajes. ",
"La aparición del Diccionario Académico ha sido polémica. ",
"La impresión de libros es más importante que otros medios de información y comunicación. ",
"Caracterizar al Quijote como un pelmazo. ",
"pueden rendir exámenes para optar y obtener títulos profesionales igual que los hombres. ",
"La biónica es una disciplina que aprovecha las condiciones del entorno. ",
"Promover la asistencia a un evento específico de decoración a través de una atractiva descripción. ",
"es una realidad discutida por algunos. ",
"Lo que es normal en un asilo es anormal en un campo de concentración. ",
"preparar los recuerdos del mañana. ",
"ritualistas y obsesivos. ",
"Mostrar cuerpos que reflejan la máxima potencia. ",
"Atraer a los turistas. ",
"Al premio merecido después de tantos esfuerzos. ",
"El hábito de la lectura y el progreso mantienen una relación inversamente proporcional. ",
"sólo las leyes bastan para gobernarse. ",
"el uranio es el elemento natural con el mayor número de protones en el núcleo. ",
"Se debe crear un seguro médico especial para esta institución, pues es de alto riesgo. ",
"A la temática satánica de las canciones del grupo. ",
"La publicidad es dañina para sus receptores. ",
"tienen dificultades durante el parto. ",
"para Aristóteles la virtud estaba en el justo equilibrio. ",
"Nuestra economía vivirá un proceso de ajuste a la nueva realidad. ",
"El derecho a informar y el derecho a la privacidad son inconciliables. ",
"la Muerte vaticina el futuro mediante gestos. ",
"para el mexicano, la muerte es cotidiana. "];

var condicion1_b = 
["Aportan informaciones con las que se reconstruye el personaje dentro de un relato. ",
"A la relación entre civilización y sociedad. ",
"El inicio de la civilización china. ",
"Las personas importantes comparten el gusto por la literatura. ",
"En los viajes es esencial el momento mismo de la escritura. ",
"Las personas escandalosas constantemente critican a la Academia. ",
"La imprenta y el papel han permitido el desarrollo de la civilización y la conservación de su cultura, y ambos son inventos chinos. ",
"Comparar a Cervantes con Quevedo. ",
"deben ser capaces de mantenerse económicamente de la misma forma que los hombres. ",
"La biónica puede asegurar nuestra existencia mediante la aplicación de técnicas copiadas de la naturaleza. ",
"Orientar la opción estética de un grupo de personas en lo que se refiere a la decoración de interiores. ",
"se da como existente, y sólo se discute su relación con el cuerpo. ",
"El concepto de normalidad es diferente para un psiquiatra que para nosotros. ",
"un recuerdo nostálgico. ",
"hedonistas y soñadores. ",
"Deleitar a sus receptores por medio de la belleza y el confort. ",
"Homenajear a quienes murieron. ",
"Al deseo de privilegiar el ocio por sobre el trabajo. ",
"Si no se lee, es imposible valorar la planificación y aceptar principios científicos. ",
"la muerte de Wu Ti fue una bendición. ",
"la creación de elementos químicos artificiales ha resultado de la manipulación del uranio. ",
"Bomberos debería tener acceso a un seguro médico, al que pueda recurrir en caso de accidente. ",
"A la inexistencia de un recinto adecuado para el recital. ",
"El receptor es habitualmente pasivo frente a la publicidad. ",
"sufren dolores de espalda. ",
"el sujeto sufre con su modo de vida. ",
"El TLC causará una completa transformación de la economía chilena. ",
"Se necesita un marco legal para delimitar lo público y lo privado en materia informativa. ",
"el jardinero era un hombre viejo. ",
"la muerte es distinta en las grandes ciudades. "];

var condicion1_c =
["Muestran las opiniones expuestas por los personajes en un relato. ",
"A la relación entre sociedad y constitución social. ",
"El inicio de la dinastía Chang. ",
"En la literatura como en la vida, lo importante son las preguntas. ",
"Los momentos triviales de los viajes, en la escritura se vuelven significativos. ",
"Las voces extranjeras viven una tensión entre la aceptación y el rechazo. ",
"Si desaparecieran el papel y la imprenta, se produciría un gran retraso en nuestra civilización. ",
"Dar a conocer al ganador del premio Cervantes. ",
"pueden ejercer profesiones científicas de la misma forma en que lo hacen los hombres. ",
"La biónica es una disciplina que tiene su origen en la ecología. ",
"Presentar positivamente las diversas tendencias del diseño de interiores a través de un comentario. ",
"es una noción que obedece a una visión pesimista de la vida. ",
"El ser humano se comporta de acuerdo con las circunstancias. ",
"la persistencia de la melancolía y la desesperanza. ",
"religiosos y precavidos. ",
"Provocar el deseo de la adquisición vertiginosa. ",
"Revivir un periodo histórico. ",
"A la inutilidad de tanto esfuerzo si el objetivo es el reposo. ",
"Las personas que leen son más flexibles en sus ideas y autónomas en su accionar. ",
"el mejor emperador es el que está muerto. ",
"a partir de la manipulación del núcleo se han creado elementos químicos naturales. ",
"Por el riesgo que corren diariamente, los bomberos deberían tener mejores condiciones de seguridad. ",
"A la influencia de grupos que rechazaban su música. ",
"La publicidad ejerce una influencia positiva sobre la sociedad. ",
"llevan un control grupal de su embarazo. ",
"el hombre excesivo es inmoral. ",
"Será difícil que las empresas nacionales compitan con las estadounidenses. ",
"La prensa tiene derecho a meter sus narices en todos lados. ",
"el jardinero estará muerto al día siguiente. ",
"para el mexicano, la muerte es como una mujer. "];

var condicion2_a = 
["Muestran las opiniones expuestas por los personajes en un relato. ",
"A la relación entre sociedad y constitución social. ",
"El inicio de la dinastía Chang. ",
"En la literatura como en la vida, lo importante son las preguntas. ",
"Los momentos triviales de los viajes, en la escritura se vuelven significativos. ",
"Las voces extranjeras viven una tensión entre la aceptación y el rechazo. ",
"Si desaparecieran el papel y la imprenta, se produciría un gran retraso en nuestra civilización. ",
"Dar a conocer al ganador del premio Cervantes. ",
"pueden ejercer profesiones científicas de la misma forma en que lo hacen los hombres. ",
"La biónica es una disciplina que tiene su origen en la ecología. ",
"Presentar positivamente las diversas tendencias del diseño de interiores a través de un comentario. ",
"es una noción que obedece a una visión pesimista de la vida. ",
"El ser humano se comporta de acuerdo con las circunstancias. ",
"la persistencia de la melancolía y la desesperanza. ",
"religiosos y precavidos. ",
"Provocar el deseo de la adquisición vertiginosa. ",
"Revivir un periodo histórico. ",
"A la inutilidad de tanto esfuerzo si el objetivo es el reposo. ",
"Las personas que leen son más flexibles en sus ideas y autónomas en su accionar. ",
"el mejor emperador es el que está muerto. ",
"a partir de la manipulación del núcleo se han creado elementos químicos naturales. ",
"Por el riesgo que corren diariamente, los bomberos deberían tener mejores condiciones de seguridad. ",
"A la influencia de grupos que rechazaban su música. ",
"La publicidad ejerce una influencia positiva sobre la sociedad. ",
"llevan un control grupal de su embarazo. ",
"el hombre excesivo es inmoral. ",
"Será difícil que las empresas nacionales compitan con las estadounidenses. ",
"La prensa tiene derecho a meter sus narices en todos lados. ",
"el jardinero estará muerto al día siguiente. ",
"para el mexicano, la muerte es como una mujer. "];

var condicion2_b = 
["Entregan una característica detallada del personaje, a través de la voz narrativa. ",
"A la relación entre pensamiento y estructura social. ",
"El origen de las grandes civilizaciones. ",
"En la literatura como en la vida, todo es metáfora. ",
"La escritura plasma los mejores momentos de los viajes. ",
"La aparición del Diccionario Académico ha sido polémica. ",
"La impresión de libros es más importante que otros medios de información y comunicación. ",
"Caracterizar al Quijote como un pelmazo. ",
"pueden rendir exámenes para optar y obtener títulos profesionales igual que los hombres. ",
"La biónica es una disciplina que aprovecha las condiciones del entorno. ",
"Promover la asistencia a un evento específico de decoración a través de una atractiva descripción. ",
"es una realidad discutida por algunos. ",
"Lo que es normal en un asilo es anormal en un campo de concentración. ",
"preparar los recuerdos del mañana. ",
"ritualistas y obsesivos. ",
"Mostrar cuerpos que reflejan la máxima potencia. ",
"Atraer a los turistas. ",
"Al premio merecido después de tantos esfuerzos. ",
"El hábito de la lectura y el progreso mantienen una relación inversamente proporcional. ",
"sólo las leyes bastan para gobernarse. ",
"el uranio es el elemento natural con el mayor número de protones en el núcleo. ",
"Se debe crear un seguro médico especial para esta institución, pues es de alto riesgo. ",
"A la temática satánica de las canciones del grupo. ",
"La publicidad es dañina para sus receptores. ",
"tienen dificultades durante el parto. ",
"para Aristóteles la virtud estaba en el justo equilibrio. ",
"Nuestra economía vivirá un proceso de ajuste a la nueva realidad. ",
"El derecho a informar y el derecho a la privacidad son inconciliables. ",
"la Muerte vaticina el futuro mediante gestos. ",
"para el mexicano, la muerte es cotidiana. "];

var condicion2_c =
["Aportan informaciones con las que se reconstruye el personaje dentro de un relato. ",
"A la relación entre civilización y sociedad. ",
"El inicio de la civilización china. ",
"Las personas importantes comparten el gusto por la literatura. ",
"En los viajes es esencial el momento mismo de la escritura. ",
"Las personas escandalosas constantemente critican a la Academia. ",
"La imprenta y el papel han permitido el desarrollo de la civilización y la conservación de su cultura, y ambos son inventos chinos. ",
"Comparar a Cervantes con Quevedo. ",
"deben ser capaces de mantenerse económicamente de la misma forma que los hombres. ",
"La biónica puede asegurar nuestra existencia mediante la aplicación de técnicas copiadas de la naturaleza. ",
"Orientar la opción estética de un grupo de personas en lo que se refiere a la decoración de interiores. ",
"se da como existente, y sólo se discute su relación con el cuerpo. ",
"El concepto de normalidad es diferente para un psiquiatra que para nosotros. ",
"un recuerdo nostálgico. ",
"hedonistas y soñadores. ",
"Deleitar a sus receptores por medio de la belleza y el confort. ",
"Homenajear a quienes murieron. ",
"Al deseo de privilegiar el ocio por sobre el trabajo. ",
"Si no se lee, es imposible valorar la planificación y aceptar principios científicos. ",
"la muerte de Wu Ti fue una bendición. ",
"la creación de elementos químicos artificiales ha resultado de la manipulación del uranio. ",
"Bomberos debería tener acceso a un seguro médico, al que pueda recurrir en caso de accidente. ",
"A la inexistencia de un recinto adecuado para el recital. ",
"El receptor es habitualmente pasivo frente a la publicidad. ",
"sufren dolores de espalda. ",
"el sujeto sufre con su modo de vida. ",
"El TLC causará una completa transformación de la economía chilena. ",
"Se necesita un marco legal para delimitar lo público y lo privado en materia informativa. ",
"el jardinero era un hombre viejo. ",
"la muerte es distinta en las grandes ciudades. "];

var condicion3_a = 
["Aportan informaciones con las que se reconstruye el personaje dentro de un relato. ",
"A la relación entre civilización y sociedad. ",
"El inicio de la civilización china. ",
"Las personas importantes comparten el gusto por la literatura. ",
"En los viajes es esencial el momento mismo de la escritura. ",
"Las personas escandalosas constantemente critican a la Academia. ",
"La imprenta y el papel han permitido el desarrollo de la civilización y la conservación de su cultura, y ambos son inventos chinos. ",
"Comparar a Cervantes con Quevedo. ",
"deben ser capaces de mantenerse económicamente de la misma forma que los hombres. ",
"La biónica puede asegurar nuestra existencia mediante la aplicación de técnicas copiadas de la naturaleza. ",
"Orientar la opción estética de un grupo de personas en lo que se refiere a la decoración de interiores. ",
"se da como existente, y sólo se discute su relación con el cuerpo. ",
"El concepto de normalidad es diferente para un psiquiatra que para nosotros. ",
"un recuerdo nostálgico. ",
"hedonistas y soñadores. ",
"Deleitar a sus receptores por medio de la belleza y el confort. ",
"Homenajear a quienes murieron. ",
"Al deseo de privilegiar el ocio por sobre el trabajo. ",
"Si no se lee, es imposible valorar la planificación y aceptar principios científicos. ",
"la muerte de Wu Ti fue una bendición. ",
"la creación de elementos químicos artificiales ha resultado de la manipulación del uranio. ",
"Bomberos debería tener acceso a un seguro médico, al que pueda recurrir en caso de accidente. ",
"A la inexistencia de un recinto adecuado para el recital. ",
"El receptor es habitualmente pasivo frente a la publicidad. ",
"sufren dolores de espalda. ",
"el sujeto sufre con su modo de vida. ",
"El TLC causará una completa transformación de la economía chilena. ",
"Se necesita un marco legal para delimitar lo público y lo privado en materia informativa. ",
"el jardinero era un hombre viejo. ",
"la muerte es distinta en las grandes ciudades. "];

var condicion3_b =
["Muestran las opiniones expuestas por los personajes en un relato. ",
"A la relación entre sociedad y constitución social. ",
"El inicio de la dinastía Chang. ",
"En la literatura como en la vida, lo importante son las preguntas. ",
"Los momentos triviales de los viajes, en la escritura se vuelven significativos. ",
"Las voces extranjeras viven una tensión entre la aceptación y el rechazo. ",
"Si desaparecieran el papel y la imprenta, se produciría un gran retraso en nuestra civilización. ",
"Dar a conocer al ganador del premio Cervantes. ",
"pueden ejercer profesiones científicas de la misma forma en que lo hacen los hombres. ",
"La biónica es una disciplina que tiene su origen en la ecología. ",
"Presentar positivamente las diversas tendencias del diseño de interiores a través de un comentario. ",
"es una noción que obedece a una visión pesimista de la vida. ",
"El ser humano se comporta de acuerdo con las circunstancias. ",
"la persistencia de la melancolía y la desesperanza. ",
"religiosos y precavidos. ",
"Provocar el deseo de la adquisición vertiginosa. ",
"Revivir un periodo histórico. ",
"A la inutilidad de tanto esfuerzo si el objetivo es el reposo. ",
"Las personas que leen son más flexibles en sus ideas y autónomas en su accionar. ",
"el mejor emperador es el que está muerto. ",
"a partir de la manipulación del núcleo se han creado elementos químicos naturales. ",
"Por el riesgo que corren diariamente, los bomberos deberían tener mejores condiciones de seguridad. ",
"A la influencia de grupos que rechazaban su música. ",
"La publicidad ejerce una influencia positiva sobre la sociedad. ",
"llevan un control grupal de su embarazo. ",
"el hombre excesivo es inmoral. ",
"Será difícil que las empresas nacionales compitan con las estadounidenses. ",
"La prensa tiene derecho a meter sus narices en todos lados. ",
"el jardinero estará muerto al día siguiente. ",
"para el mexicano, la muerte es como una mujer. "];

var condicion3_c = 
["Entregan una característica detallada del personaje, a través de la voz narrativa. ",
"A la relación entre pensamiento y estructura social. ",
"El origen de las grandes civilizaciones. ",
"En la literatura como en la vida, todo es metáfora. ",
"La escritura plasma los mejores momentos de los viajes. ",
"La aparición del Diccionario Académico ha sido polémica. ",
"La impresión de libros es más importante que otros medios de información y comunicación. ",
"Caracterizar al Quijote como un pelmazo. ",
"pueden rendir exámenes para optar y obtener títulos profesionales igual que los hombres. ",
"La biónica es una disciplina que aprovecha las condiciones del entorno. ",
"Promover la asistencia a un evento específico de decoración a través de una atractiva descripción. ",
"es una realidad discutida por algunos. ",
"Lo que es normal en un asilo es anormal en un campo de concentración. ",
"preparar los recuerdos del mañana. ",
"ritualistas y obsesivos. ",
"Mostrar cuerpos que reflejan la máxima potencia. ",
"Atraer a los turistas. ",
"Al premio merecido después de tantos esfuerzos. ",
"El hábito de la lectura y el progreso mantienen una relación inversamente proporcional. ",
"sólo las leyes bastan para gobernarse. ",
"el uranio es el elemento natural con el mayor número de protones en el núcleo. ",
"Se debe crear un seguro médico especial para esta institución, pues es de alto riesgo. ",
"A la temática satánica de las canciones del grupo. ",
"La publicidad es dañina para sus receptores. ",
"tienen dificultades durante el parto. ",
"para Aristóteles la virtud estaba en el justo equilibrio. ",
"Nuestra economía vivirá un proceso de ajuste a la nueva realidad. ",
"El derecho a informar y el derecho a la privacidad son inconciliables. ",
"la Muerte vaticina el futuro mediante gestos. ",
"para el mexicano, la muerte es cotidiana. "];

var condicion4_a = 
["Muestran las opiniones expuestas por los personajes en un relato. ",
"A la relación entre pensamiento y estructura social. ",
"El inicio de la dinastía Chang. ",
"Las personas importantes comparten el gusto por la literatura. ",
"En los viajes es esencial el momento mismo de la escritura. ",
"Las personas escandalosas constantemente critican a la Academia. ",
"Si desaparecieran el papel y la imprenta, se produciría un gran retraso en nuestra civilización. ",
"Comparar a Cervantes con Quevedo. ",
"pueden rendir exámenes para optar y obtener títulos profesionales igual que los hombres. ",
"La biónica es una disciplina que tiene su origen en la ecología. ",
"Promover la asistencia a un evento específico de decoración a través de una atractiva descripción. ",
"es una noción que obedece a una visión pesimista de la vida. ",
"El concepto de normalidad es diferente para un psiquiatra que para nosotros. ",
"preparar los recuerdos del mañana. ",
"ritualistas y obsesivos. ",
"Deleitar a sus receptores por medio de la belleza y el confort. ",
"Revivir un periodo histórico. ",
"Al premio merecido después de tantos esfuerzos. ",
"Si no se lee, es imposible valorar la planificación y aceptar principios científicos. ",
"la muerte de Wu Ti fue una bendición. ",
"el uranio es el elemento natural con el mayor número de protones en el núcleo. ",
"Por el riesgo que corren diariamente, los bomberos deberían tener mejores condiciones de seguridad. ",
"A la inexistencia de un recinto adecuado para el recital. ",
"La publicidad ejerce una influencia positiva sobre la sociedad. ",
"llevan un control grupal de su embarazo. ",
"para Aristóteles la virtud estaba en el justo equilibrio. ",
"Nuestra economía vivirá un proceso de ajuste a la nueva realidad. ",
"La prensa tiene derecho a meter sus narices en todos lados. ",
"el jardinero era un hombre viejo. ",
"para el mexicano, la muerte es cotidiana. "];

var condicion4_b =
["Aportan informaciones con las que se reconstruye el personaje dentro de un relato. ",
"A la relación entre sociedad y constitución social. ",
"El inicio de la civilización china. ",
"En la literatura como en la vida, todo es metáfora. ",
"La escritura plasma los mejores momentos de los viajes. ",
"La aparición del Diccionario Académico ha sido polémica. ",
"La imprenta y el papel han permitido el desarrollo de la civilización y la conservación de su cultura, y ambos son inventos chinos. ",
"Caracterizar al Quijote como un pelmazo. ",
"pueden ejercer profesiones científicas de la misma forma en que lo hacen los hombres. ",
"La biónica puede asegurar nuestra existencia mediante la aplicación de técnicas copiadas de la naturaleza. ",
"Presentar positivamente las diversas tendencias del diseño de interiores a través de un comentario. ",
"se da como existente, y sólo se discute su relación con el cuerpo. ",
"Lo que es normal en un asilo es anormal en un campo de concentración. ",
"la persistencia de la melancolía y la desesperanza. ",
"religiosos y precavidos. ",
"Mostrar cuerpos que reflejan la máxima potencia. ",
"Homenajear a quienes murieron. ",
"A la inutilidad de tanto esfuerzo si el objetivo es el reposo. ",
"El hábito de la lectura y el progreso mantienen una relación inversamente proporcional. ",
"sólo las leyes bastan para gobernarse. ",
"a partir de la manipulación del núcleo se han creado elementos químicos naturales. ",
"Bomberos debería tener acceso a un seguro médico, al que pueda recurrir en caso de accidente. ",
"A la temática satánica de las canciones del grupo. ",
"El receptor es habitualmente pasivo frente a la publicidad. ",
"sufren dolores de espalda. ",
"el hombre excesivo es inmoral. ",
"Será difícil que las empresas nacionales compitan con las estadounidenses. ",
"Se necesita un marco legal para delimitar lo público y lo privado en materia informativa. ",
"la Muerte vaticina el futuro mediante gestos. ",
"para el mexicano, la muerte es como una mujer. "];

var condicion4_c =
["Entregan una característica detallada del personaje, a través de la voz narrativa. ",
"A la relación entre civilización y sociedad. ",
"El origen de las grandes civilizaciones. ",
"En la literatura como en la vida, lo importante son las preguntas. ",
"Los momentos triviales de los viajes, en la escritura se vuelven significativos. ",
"Las voces extranjeras viven una tensión entre la aceptación y el rechazo. ",
"La impresión de libros es más importante que otros medios de información y comunicación. ",
"Dar a conocer al ganador del premio Cervantes. ",
"deben ser capaces de mantenerse económicamente de la misma forma que los hombres. ",
"La biónica es una disciplina que aprovecha las condiciones del entorno. ",
"Orientar la opción estética de un grupo de personas en lo que se refiere a la decoración de interiores. ",
"es una realidad discutida por algunos. ",
"El ser humano se comporta de acuerdo con las circunstancias. ",
"un recuerdo nostálgico. ",
"hedonistas y soñadores. ",
"Provocar el deseo de la adquisición vertiginosa. ",
"Atraer a los turistas. ",
"Al deseo de privilegiar el ocio por sobre el trabajo. ",
"Las personas que leen son más flexibles en sus ideas y autónomas en su accionar. ",
"el mejor emperador es el que está muerto. ",
"la creación de elementos químicos artificiales ha resultado de la manipulación del uranio. ",
"Se debe crear un seguro médico especial para esta institución, pues es de alto riesgo. ",
"A la influencia de grupos que rechazaban su música. ",
"La publicidad es dañina para sus receptores. ",
"tienen dificultades durante el parto. ",
"el sujeto sufre con su modo de vida. ",
"El TLC causará una completa transformación de la economía chilena. ",
"El derecho a informar y el derecho a la privacidad son inconciliables. ",
"el jardinero estará muerto al día siguiente. ",
"la muerte es distinta en las grandes ciudades. "];

var condicion5_a =
["Entregan una característica detallada del personaje, a través de la voz narrativa. ",
"A la relación entre civilización y sociedad. ",
"El origen de las grandes civilizaciones. ",
"En la literatura como en la vida, lo importante son las preguntas. ",
"Los momentos triviales de los viajes, en la escritura se vuelven significativos. ",
"Las voces extranjeras viven una tensión entre la aceptación y el rechazo. ",
"La impresión de libros es más importante que otros medios de información y comunicación. ",
"Dar a conocer al ganador del premio Cervantes. ",
"deben ser capaces de mantenerse económicamente de la misma forma que los hombres. ",
"La biónica es una disciplina que aprovecha las condiciones del entorno. ",
"Orientar la opción estética de un grupo de personas en lo que se refiere a la decoración de interiores. ",
"es una realidad discutida por algunos. ",
"El ser humano se comporta de acuerdo con las circunstancias. ",
"un recuerdo nostálgico. ",
"hedonistas y soñadores. ",
"Provocar el deseo de la adquisición vertiginosa. ",
"Atraer a los turistas. ",
"Al deseo de privilegiar el ocio por sobre el trabajo. ",
"Las personas que leen son más flexibles en sus ideas y autónomas en su accionar. ",
"el mejor emperador es el que está muerto. ",
"la creación de elementos químicos artificiales ha resultado de la manipulación del uranio. ",
"Se debe crear un seguro médico especial para esta institución, pues es de alto riesgo. ",
"A la influencia de grupos que rechazaban su música. ",
"La publicidad es dañina para sus receptores. ",
"tienen dificultades durante el parto. ",
"el sujeto sufre con su modo de vida. ",
"El TLC causará una completa transformación de la economía chilena. ",
"El derecho a informar y el derecho a la privacidad son inconciliables. ",
"el jardinero estará muerto al día siguiente. ",
"la muerte es distinta en las grandes ciudades. "];

var condicion5_b =
["Muestran las opiniones expuestas por los personajes en un relato. ",
"A la relación entre pensamiento y estructura social. ",
"El inicio de la dinastía Chang. ",
"Las personas importantes comparten el gusto por la literatura. ",
"En los viajes es esencial el momento mismo de la escritura. ",
"Las personas escandalosas constantemente critican a la Academia. ",
"Si desaparecieran el papel y la imprenta, se produciría un gran retraso en nuestra civilización. ",
"Comparar a Cervantes con Quevedo. ",
"pueden rendir exámenes para optar y obtener títulos profesionales igual que los hombres. ",
"La biónica es una disciplina que tiene su origen en la ecología. ",
"Promover la asistencia a un evento específico de decoración a través de una atractiva descripción. ",
"es una noción que obedece a una visión pesimista de la vida. ",
"El concepto de normalidad es diferente para un psiquiatra que para nosotros. ",
"preparar los recuerdos del mañana. ",
"ritualistas y obsesivos. ",
"Deleitar a sus receptores por medio de la belleza y el confort. ",
"Revivir un periodo histórico. ",
"Al premio merecido después de tantos esfuerzos. ",
"Si no se lee, es imposible valorar la planificación y aceptar principios científicos. ",
"la muerte de Wu Ti fue una bendición. ",
"el uranio es el elemento natural con el mayor número de protones en el núcleo. ",
"Por el riesgo que corren diariamente, los bomberos deberían tener mejores condiciones de seguridad. ",
"A la inexistencia de un recinto adecuado para el recital. ",
"La publicidad ejerce una influencia positiva sobre la sociedad. ",
"llevan un control grupal de su embarazo. ",
"para Aristóteles la virtud estaba en el justo equilibrio. ",
"Nuestra economía vivirá un proceso de ajuste a la nueva realidad. ",
"La prensa tiene derecho a meter sus narices en todos lados. ",
"el jardinero era un hombre viejo. ",
"para el mexicano, la muerte es cotidiana. "];

var condicion5_c = 
["Aportan informaciones con las que se reconstruye el personaje dentro de un relato. ",
"A la relación entre sociedad y constitución social. ",
"El inicio de la civilización china. ",
"En la literatura como en la vida, todo es metáfora. ",
"La escritura plasma los mejores momentos de los viajes. ",
"La aparición del Diccionario Académico ha sido polémica. ",
"La imprenta y el papel han permitido el desarrollo de la civilización y la conservación de su cultura, y ambos son inventos chinos. ",
"Caracterizar al Quijote como un pelmazo. ",
"pueden ejercer profesiones científicas de la misma forma en que lo hacen los hombres. ",
"La biónica puede asegurar nuestra existencia mediante la aplicación de técnicas copiadas de la naturaleza. ",
"Presentar positivamente las diversas tendencias del diseño de interiores a través de un comentario. ",
"se da como existente, y sólo se discute su relación con el cuerpo. ",
"Lo que es normal en un asilo es anormal en un campo de concentración. ",
"la persistencia de la melancolía y la desesperanza. ",
"religiosos y precavidos. ",
"Mostrar cuerpos que reflejan la máxima potencia. ",
"Homenajear a quienes murieron. ",
"A la inutilidad de tanto esfuerzo si el objetivo es el reposo. ",
"El hábito de la lectura y el progreso mantienen una relación inversamente proporcional. ",
"sólo las leyes bastan para gobernarse. ",
"a partir de la manipulación del núcleo se han creado elementos químicos naturales. ",
"Bomberos debería tener acceso a un seguro médico, al que pueda recurrir en caso de accidente. ",
"A la temática satánica de las canciones del grupo. ",
"El receptor es habitualmente pasivo frente a la publicidad. ",
"sufren dolores de espalda. ",
"el hombre excesivo es inmoral. ",
"Será difícil que las empresas nacionales compitan con las estadounidenses. ",
"Se necesita un marco legal para delimitar lo público y lo privado en materia informativa. ",
"la Muerte vaticina el futuro mediante gestos. ",
"para el mexicano, la muerte es como una mujer. "];

var condicion6_a =
["Aportan informaciones con las que se reconstruye el personaje dentro de un relato. ",
"A la relación entre sociedad y constitución social. ",
"El inicio de la civilización china. ",
"En la literatura como en la vida, todo es metáfora. ",
"La escritura plasma los mejores momentos de los viajes. ",
"La aparición del Diccionario Académico ha sido polémica. ",
"La imprenta y el papel han permitido el desarrollo de la civilización y la conservación de su cultura, y ambos son inventos chinos. ",
"Caracterizar al Quijote como un pelmazo. ",
"pueden ejercer profesiones científicas de la misma forma en que lo hacen los hombres. ",
"La biónica puede asegurar nuestra existencia mediante la aplicación de técnicas copiadas de la naturaleza. ",
"Presentar positivamente las diversas tendencias del diseño de interiores a través de un comentario. ",
"se da como existente, y sólo se discute su relación con el cuerpo. ",
"Lo que es normal en un asilo es anormal en un campo de concentración. ",
"la persistencia de la melancolía y la desesperanza. ",
"religiosos y precavidos. ",
"Mostrar cuerpos que reflejan la máxima potencia. ",
"Homenajear a quienes murieron. ",
"A la inutilidad de tanto esfuerzo si el objetivo es el reposo. ",
"El hábito de la lectura y el progreso mantienen una relación inversamente proporcional. ",
"sólo las leyes bastan para gobernarse. ",
"a partir de la manipulación del núcleo se han creado elementos químicos naturales. ",
"Bomberos debería tener acceso a un seguro médico, al que pueda recurrir en caso de accidente. ",
"A la temática satánica de las canciones del grupo. ",
"El receptor es habitualmente pasivo frente a la publicidad. ",
"sufren dolores de espalda. ",
"el hombre excesivo es inmoral. ",
"Será difícil que las empresas nacionales compitan con las estadounidenses. ",
"Se necesita un marco legal para delimitar lo público y lo privado en materia informativa. ",
"la Muerte vaticina el futuro mediante gestos. ",
"para el mexicano, la muerte es como una mujer. "];

var condicion6_b =
["Entregan una característica detallada del personaje, a través de la voz narrativa. ",
"A la relación entre civilización y sociedad. ",
"El origen de las grandes civilizaciones. ",
"En la literatura como en la vida, lo importante son las preguntas. ",
"Los momentos triviales de los viajes, en la escritura se vuelven significativos. ",
"Las voces extranjeras viven una tensión entre la aceptación y el rechazo. ",
"La impresión de libros es más importante que otros medios de información y comunicación. ",
"Dar a conocer al ganador del premio Cervantes. ",
"deben ser capaces de mantenerse económicamente de la misma forma que los hombres. ",
"La biónica es una disciplina que aprovecha las condiciones del entorno. ",
"Orientar la opción estética de un grupo de personas en lo que se refiere a la decoración de interiores. ",
"es una realidad discutida por algunos. ",
"El ser humano se comporta de acuerdo con las circunstancias. ",
"un recuerdo nostálgico. ",
"hedonistas y soñadores. ",
"Provocar el deseo de la adquisición vertiginosa. ",
"Atraer a los turistas. ",
"Al deseo de privilegiar el ocio por sobre el trabajo. ",
"Las personas que leen son más flexibles en sus ideas y autónomas en su accionar. ",
"el mejor emperador es el que está muerto. ",
"la creación de elementos químicos artificiales ha resultado de la manipulación del uranio. ",
"Se debe crear un seguro médico especial para esta institución, pues es de alto riesgo. ",
"A la influencia de grupos que rechazaban su música. ",
"La publicidad es dañina para sus receptores. ",
"tienen dificultades durante el parto. ",
"el sujeto sufre con su modo de vida. ",
"El TLC causará una completa transformación de la economía chilena. ",
"El derecho a informar y el derecho a la privacidad son inconciliables. ",
"el jardinero estará muerto al día siguiente. ",
"la muerte es distinta en las grandes ciudades. "];

var condicion6_c =
["Muestran las opiniones expuestas por los personajes en un relato. ",
"A la relación entre pensamiento y estructura social. ",
"El inicio de la dinastía Chang. ",
"Las personas importantes comparten el gusto por la literatura. ",
"En los viajes es esencial el momento mismo de la escritura. ",
"Las personas escandalosas constantemente critican a la Academia. ",
"Si desaparecieran el papel y la imprenta, se produciría un gran retraso en nuestra civilización. ",
"Comparar a Cervantes con Quevedo. ",
"pueden rendir exámenes para optar y obtener títulos profesionales igual que los hombres. ",
"La biónica es una disciplina que tiene su origen en la ecología. ",
"Promover la asistencia a un evento específico de decoración a través de una atractiva descripción. ",
"es una noción que obedece a una visión pesimista de la vida. ",
"El concepto de normalidad es diferente para un psiquiatra que para nosotros. ",
"preparar los recuerdos del mañana. ",
"ritualistas y obsesivos. ",
"Deleitar a sus receptores por medio de la belleza y el confort. ",
"Revivir un periodo histórico. ",
"Al premio merecido después de tantos esfuerzos. ",
"Si no se lee, es imposible valorar la planificación y aceptar principios científicos. ",
"la muerte de Wu Ti fue una bendición. ",
"el uranio es el elemento natural con el mayor número de protones en el núcleo. ",
"Por el riesgo que corren diariamente, los bomberos deberían tener mejores condiciones de seguridad. ",
"A la inexistencia de un recinto adecuado para el recital. ",
"La publicidad ejerce una influencia positiva sobre la sociedad. ",
"llevan un control grupal de su embarazo. ",
"para Aristóteles la virtud estaba en el justo equilibrio. ",
"Nuestra economía vivirá un proceso de ajuste a la nueva realidad. ",
"La prensa tiene derecho a meter sus narices en todos lados. ",
"el jardinero era un hombre viejo. ",
"para el mexicano, la muerte es cotidiana. "];
// estilo css 
var estilo_contexto = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 13%; margin-left: 13%; margin-top: 5%">';
var estilo_preguntas = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 13%; margin-left: 13%; margin-top: 1%">';
// Estilo css preguntas con opciones con distinto numero de lineas entre opciones
var estilo_contexto_0 = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 17%; margin-left: 17%; margin-top: 5%">';
var estilo_preguntas_0 = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 17%; margin-left: 17%; margin-top: 1%">';
var estilo_contexto_1 = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 24%; margin-left: 24%; margin-top: 5%">';
var estilo_preguntas_1 = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 24%; margin-left: 24%; margin-top: 1%">';
var estilo_contexto_2 = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 17%; margin-left: 17%; margin-top: 5%">';
var estilo_preguntas_2 = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 17%; margin-left: 17%; margin-top: 1%">';
var estilo_contexto_3 = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 7%; margin-left: 7%; margin-top: 5%">';
var estilo_preguntas_3 = '<p style="font-size: 120%; text-align:left; justify-content:space-between; margin-right: 7%; margin-left: 7%; margin-top: 1%">';
// Funcion que retorna la condición indicada en su argumento
function MCQ_data_condition(condicion) {
    // declaro la variable de datos
    var MCQ_data = [];
    for (i = 0; i < 30; i++) {
        // declarar el orden de las opciones
        var opciones_cond = []
        if (condicion == 1){
            // condicion 1
            opciones_cond.push(("a) ").concat(condicion1_a[i]));
            opciones_cond.push(("b) ").concat(condicion1_b[i]));
            opciones_cond.push(("c) ").concat(condicion1_c[i]));
        }
        else if (condicion == 2){
            // condicion 2
            opciones_cond.push(("a) ").concat(condicion2_a[i]));
            opciones_cond.push(("b) ").concat(condicion2_b[i]));
            opciones_cond.push(("c) ").concat(condicion2_c[i]));
        }
        else if (condicion == 3){
            // condicion 3
            opciones_cond.push(("a) ").concat(condicion3_a[i]));
            opciones_cond.push(("b) ").concat(condicion3_b[i]));
            opciones_cond.push(("c) ").concat(condicion3_c[i]));
        }
        else if (condicion == 4){
            // condicion 4
            opciones_cond.push(("a) ").concat(condicion4_a[i]));
            opciones_cond.push(("b) ").concat(condicion4_b[i]));
            opciones_cond.push(("c) ").concat(condicion4_c[i]));
        }
        else if (condicion == 5){
            // condicion 5
            opciones_cond.push(("a) ").concat(condicion5_a[i]));
            opciones_cond.push(("b) ").concat(condicion5_b[i]));
            opciones_cond.push(("c) ").concat(condicion5_c[i]));
        }
        else {
            // condicion 6
            opciones_cond.push(("a) ").concat(condicion6_a[i]));
            opciones_cond.push(("b) ").concat(condicion6_b[i]));
            opciones_cond.push(("c) ").concat(condicion6_c[i]));
        }        
        if ((i == 6)){
             // agregar objeto questions a la lista MCQ data
             MCQ_data.push(
                {questions: 
                [{prompt: estilo_contexto_0+(contexto[i])+estilo_preguntas_0+(preguntas[i]), 
                name: 'pregunta'.concat((i+1).toString()), 
                options: opciones_cond,
                required:true,
                margin: 'margin-right: 21%; margin-left: 15%;'}]}
            )
        } else if ((i == 9)){
            // agregar objeto questions a la lista MCQ data
            MCQ_data.push(
               {questions: 
               [{prompt: estilo_contexto_1+(contexto[i])+estilo_preguntas_1+(preguntas[i]), 
               name: 'pregunta'.concat((i+1).toString()), 
               options: opciones_cond,
               required:true,
               margin: 'margin-right: 28%; margin-left: 22%;'}]}
           )
       } else if ((i == 10)){
        // agregar objeto questions a la lista MCQ data
        MCQ_data.push(
           {questions: 
           [{prompt: estilo_contexto_2+(contexto[i])+estilo_preguntas_2+(preguntas[i]), 
           name: 'pregunta'.concat((i+1).toString()), 
           options: opciones_cond,
           required:true,
           margin: 'margin-right: 19%; margin-left: 15%;'}]}
       )
   } 
 else if ((i == 21)){
    // agregar objeto questions a la lista MCQ data
    MCQ_data.push(
       {questions: 
       [{prompt: estilo_contexto_3+(contexto[i])+estilo_preguntas_3+(preguntas[i]), 
       name: 'pregunta'.concat((i+1).toString()), 
       options: opciones_cond,
       required:true,
       margin: 'margin-right: 9%; margin-left: 5%;'}]}
   )
} 
        
        
        
        
        
        
        else {
            // agregar objeto questions a la lista MCQ data
            MCQ_data.push(
                {questions: 
                [{prompt: estilo_contexto+(contexto[i])+estilo_preguntas+(preguntas[i]), 
                name: 'pregunta'.concat((i+1).toString()), 
                options: opciones_cond,
                required:true,
                normal_margin: true}]}
            )
        }
        
    }   
    return MCQ_data;  
}
// Data Likert seguridad
// Escala likert de seguridad
var scale = ['<span style="font-size: 130%;">para nada <br>seguro(a)</span>',
            '<span style="font-size: 130%;">no muy <br>seguro(a)</span>', 
            '<span style="font-size: 130%;">bastante <br>seguro(a)</span>', 
            '<span style="font-size: 130%;">totalmente <br>seguro(a)</span>'
];
var pregunta_seguridad = '<p style="font-size: 150%;"> ¿Qué tan seguro(a) estás de tu respuesta?</p>';