<p><strong>Posici&oacute;n postdoctoral  en CIAE - DEMRE, Universidad de Chile.</strong><p></p>
  Dos nuevos puestos postdoctorales se ofrecen en el Centro de  Investigaci&oacute;n Avanzada en Educaci&oacute;n (CIAE) en una unidad de investigaci&oacute;n  conjunta con el Departamento de Medici&oacute;n Evaluaci&oacute;n y Registro Educacional (DEMRE),  ambos de la Universidad de Chile<p></p>
  Los candidatos deben mostrar evidencia de una producci&oacute;n  destacada en investigaci&oacute;n y de haber obtenido el grado de doctor en  Estad&iacute;stica, Psicometr&iacute;a, Evaluaci&oacute;n o en &aacute;reas afines, no antes de 2010. <p></p>
  Los puestos que se ofrecen son para desarrollar actividad de  investigaci&oacute;n a tiempo completo, sin obligaciones docentes. La preparaci&oacute;n de  los candidatos y sus intereses deber&aacute;n permitirles contribuir a desarrollar la  agenda de investigaci&oacute;n del DEMRE, que incluye estudios tendientes a mejorar  los instrumentos de evaluaci&oacute;n actualmente en uso y generar nuevos instrumentos  de evaluaci&oacute;n, as&iacute; como estudios a partir de la gran acumulaci&oacute;n de datos  hist&oacute;ricos disponibles en DEMRE para entregar evidencia que contribuya a  informar la pol&iacute;tica educativa nacional.<p></p>
  Estos puestos de trabajo son por un a&ntilde;o, prorrogable por el  mismo per&iacute;odo hasta un total de tres a&ntilde;os. Los investigadores postdoctorales  seleccionados ser&aacute;n evaluados al final de cada per&iacute;odo de acuerdo a los  est&aacute;ndares de excelencia CIAE.<p></p>
  CIAE cubrir&aacute; pasajes de avi&oacute;n, pagar&aacute; un salario mensual de  alrededor de $1.575.000 CLP y pagar&aacute; los costos de divulgaci&oacute;n relacionada, sujeta  a evaluaci&oacute;n. Sin embargo, se espera que los investigadores postdoctorales  seleccionados postulen a fondos concursables nacionales de financiamiento de la  investigaci&oacute;n. No se requiere dominio de la lengua espa&ntilde;ola.
  <p></p>
  No se ha fijado una fecha de inicio, pero deben comenzar  preferentemente antes de marzo de 2016. El proceso de postulaci&oacute;n estar&aacute;  abierto hasta el <strong>15 de enero del 2016</strong>.<p></p>
  Despu&eacute;s de llenar el formulario de postulaci&oacute;n, usted recibir&aacute; un email  de confirmaci&oacute;n con un enlace que debe enviar a las personas que van a escribir  sus cartas de recomendaci&oacute;n.
  <p></p>
  Las aplicaciones que no reciban tres recomendaciones a la  fecha l&iacute;mite de postulaci&oacute;n ser&aacute;n declaradas vac&iacute;as.</p>
<hr>
<p><strong>Postdoctoral  position at CIAE - DEMRE, Universidad de Chile.</strong><p></p>
  Two new  postdoctoral positions are being offered at the Center for Advanced Research in  Education (CIAE) in a joint Research Unit with the Department for Educational  Assessment (DEMRE), both at the Universidad de Chile.<p></p>
  Candidates  should exhibit evidence of outstanding research results and should have  received a PhD in Statistics, Psychometrics, Assessment or related fields by  the beginning of the appointment and not before 2010. The position is for  full-time research activity, with no teaching duties, and with expected  participation in conferences or workshops in Chile or abroad. The preparation  of the candidates and their interests should enable them to contribute to  developing the research agenda of DEMRE, including studies to improve  assessment instruments currently in use as well as the design of new assessment  instruments and studies that use the large accumulation of historical data  available in DEMRE, to support and inform national educational policy. Positions  are for one year, renewable for the same period up to three years. Selected  postdocs will be evaluated at the end of each period according to the CIAE  excellence standards.<p></p>
  CIAE will  cover flight tickets, and will pay a monthly salary of around US$2,250 as well  as paying for outreach related costs, subject to evaluation. Nevertheless,  selected postdocs are expected to apply for national grants and research  funding. Spanish language is not required.<p></p>
  Appointments  have no fixed starting date, but should preferably start no later than March  2016. The application process will be open until <strong>March 31, 2016</strong>.<strong> </strong><p></p>
  After completing the application form you will receive a confirmation email with a link that you must send  to the people who will write your recommendation letters.
  <p></p>
Applications  for which three recommendations are not received by the application deadline  will be declared abandoned.</p>
