<option value="">----------</option>
<option value="2" {selected_codigo_area_option_2}>2</option>
<option value="32"  {selected_codigo_area_option_32}>32</option>
<option value="33"  {selected_codigo_area_option_33}>33</option>
<option value="34"  {selected_codigo_area_option_34}>34</option>
<option value="35"  {selected_codigo_area_option_35}>35</option>
<option value="41"  {selected_codigo_area_option_41}>41</option>
<option value="42"  {selected_codigo_area_option_42}>42</option>
<option value="43"  {selected_codigo_area_option_43}>43</option>
<option value="44"  {selected_codigo_area_option_43}>44</option>
<option value="45"  {selected_codigo_area_option_45}>45</option>
<option value="51"  {selected_codigo_area_option_51}>51</option>
<option value="52"  {selected_codigo_area_option_52}>52</option>
<option value="53"  {selected_codigo_area_option_53}>53</option>
<option value="55"  {selected_codigo_area_option_55}>55</option>
<option value="57"  {selected_codigo_area_option_57}>57</option>
<option value="58"  {selected_codigo_area_option_58}>58</option>
<option value="61"  {selected_codigo_area_option_61}>61</option> 
<option value="63"  {selected_codigo_area_option_63}>63</option>
<option value="64"  {selected_codigo_area_option_64}>64</option>
<option value="65"  {selected_codigo_area_option_65}>65</option>
<option value="67"  {selected_codigo_area_option_67}>67</option>
<option value="71"  {selected_codigo_area_option_71}>71</option>
<option value="72"  {selected_codigo_area_option_72}>72</option>
<option value="73"  {selected_codigo_area_option_73}>73</option>
<option value="75"  {selected_codigo_area_option_75}>75</option>
<option value="02" {selected_codigo_area_option_2}>2</option>
 